# Generated by Django 5.1.15 on 2026-10-09 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('EXECUTIVE_SUMMARY', 'Executive Examination Summary'), ('READINESS_INDEX', 'Examination Readiness Index'), ('ROOM_UTILIZATION', 'Room & Infrastructure Utilization'), ('SEATING_COMPLETION', 'Seating Arrangement Report'), ('INVIGILATION_WORKLOAD', 'Invigilator Workload Distribution'), ('ATTENDANCE_SUMMARY', 'Examination Attendance & Malpractice Report')], max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('file_format', models.CharField(default='PDF', max_length=10)),
                ('file_path', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
