"""
Rabindranath Tagore Academic Pavilion Blueprint
ExamForge Facilities & Infrastructure Registry
"""

COMPLEX_NAME = "Rabindranath Tagore Academic Pavilion Blueprint"

ROOM_SPECIFICATIONS = [
    {
        "room_number": "HUM-101",
        "floor": 1,
        "total_area_sqft": 1400,
        "usable_capacity": 36,
        "physical_capacity": 42,
        "grid": {"rows": 6, "columns": 7},
        "cctv_cameras": [
            {"cam_id": "CAM-101-FRONT", "coverage": "Podium & Rows 1-3", "resolution": "4K UHD"},
            {"cam_id": "CAM-101-REAR", "coverage": "Entrance & Rows 4-6", "resolution": "4K UHD"},
        ],
        "accessibility": {"wheelchair_ramp": True, "tactile_path": True, "wide_entrance": True},
        "power_backup": {"ups_inverter": True, "generator_line": True, "battery_runtime_min": 180},
        "inspection_checkpoints": [
            "Checkpoint 1: Inspection of bench structural integrity and numbered desk decal stability 1",
            "Checkpoint 1.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 2: Inspection of bench structural integrity and numbered desk decal stability 2",
            "Checkpoint 2.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 3: Inspection of bench structural integrity and numbered desk decal stability 3",
            "Checkpoint 3.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 4: Inspection of bench structural integrity and numbered desk decal stability 4",
            "Checkpoint 4.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 5: Inspection of bench structural integrity and numbered desk decal stability 5",
            "Checkpoint 5.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 6: Inspection of bench structural integrity and numbered desk decal stability 6",
            "Checkpoint 6.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 7: Inspection of bench structural integrity and numbered desk decal stability 7",
            "Checkpoint 7.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 8: Inspection of bench structural integrity and numbered desk decal stability 8",
            "Checkpoint 8.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
        ],
    },
    {
        "room_number": "HUM-102",
        "floor": 1,
        "total_area_sqft": 1400,
        "usable_capacity": 36,
        "physical_capacity": 42,
        "grid": {"rows": 6, "columns": 7},
        "cctv_cameras": [
            {"cam_id": "CAM-102-FRONT", "coverage": "Podium & Rows 1-3", "resolution": "4K UHD"},
            {"cam_id": "CAM-102-REAR", "coverage": "Entrance & Rows 4-6", "resolution": "4K UHD"},
        ],
        "accessibility": {"wheelchair_ramp": True, "tactile_path": True, "wide_entrance": True},
        "power_backup": {"ups_inverter": True, "generator_line": True, "battery_runtime_min": 180},
        "inspection_checkpoints": [
            "Checkpoint 1: Inspection of bench structural integrity and numbered desk decal stability 1",
            "Checkpoint 1.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 2: Inspection of bench structural integrity and numbered desk decal stability 2",
            "Checkpoint 2.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 3: Inspection of bench structural integrity and numbered desk decal stability 3",
            "Checkpoint 3.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 4: Inspection of bench structural integrity and numbered desk decal stability 4",
            "Checkpoint 4.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 5: Inspection of bench structural integrity and numbered desk decal stability 5",
            "Checkpoint 5.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 6: Inspection of bench structural integrity and numbered desk decal stability 6",
            "Checkpoint 6.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 7: Inspection of bench structural integrity and numbered desk decal stability 7",
            "Checkpoint 7.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 8: Inspection of bench structural integrity and numbered desk decal stability 8",
            "Checkpoint 8.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
        ],
    },
    {
        "room_number": "HUM-103",
        "floor": 1,
        "total_area_sqft": 1400,
        "usable_capacity": 36,
        "physical_capacity": 42,
        "grid": {"rows": 6, "columns": 7},
        "cctv_cameras": [
            {"cam_id": "CAM-103-FRONT", "coverage": "Podium & Rows 1-3", "resolution": "4K UHD"},
            {"cam_id": "CAM-103-REAR", "coverage": "Entrance & Rows 4-6", "resolution": "4K UHD"},
        ],
        "accessibility": {"wheelchair_ramp": True, "tactile_path": True, "wide_entrance": True},
        "power_backup": {"ups_inverter": True, "generator_line": True, "battery_runtime_min": 180},
        "inspection_checkpoints": [
            "Checkpoint 1: Inspection of bench structural integrity and numbered desk decal stability 1",
            "Checkpoint 1.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 2: Inspection of bench structural integrity and numbered desk decal stability 2",
            "Checkpoint 2.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 3: Inspection of bench structural integrity and numbered desk decal stability 3",
            "Checkpoint 3.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 4: Inspection of bench structural integrity and numbered desk decal stability 4",
            "Checkpoint 4.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 5: Inspection of bench structural integrity and numbered desk decal stability 5",
            "Checkpoint 5.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 6: Inspection of bench structural integrity and numbered desk decal stability 6",
            "Checkpoint 6.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 7: Inspection of bench structural integrity and numbered desk decal stability 7",
            "Checkpoint 7.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 8: Inspection of bench structural integrity and numbered desk decal stability 8",
            "Checkpoint 8.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
        ],
    },
    {
        "room_number": "HUM-104",
        "floor": 1,
        "total_area_sqft": 1400,
        "usable_capacity": 36,
        "physical_capacity": 42,
        "grid": {"rows": 6, "columns": 7},
        "cctv_cameras": [
            {"cam_id": "CAM-104-FRONT", "coverage": "Podium & Rows 1-3", "resolution": "4K UHD"},
            {"cam_id": "CAM-104-REAR", "coverage": "Entrance & Rows 4-6", "resolution": "4K UHD"},
        ],
        "accessibility": {"wheelchair_ramp": True, "tactile_path": True, "wide_entrance": True},
        "power_backup": {"ups_inverter": True, "generator_line": True, "battery_runtime_min": 180},
        "inspection_checkpoints": [
            "Checkpoint 1: Inspection of bench structural integrity and numbered desk decal stability 1",
            "Checkpoint 1.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 2: Inspection of bench structural integrity and numbered desk decal stability 2",
            "Checkpoint 2.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 3: Inspection of bench structural integrity and numbered desk decal stability 3",
            "Checkpoint 3.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 4: Inspection of bench structural integrity and numbered desk decal stability 4",
            "Checkpoint 4.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 5: Inspection of bench structural integrity and numbered desk decal stability 5",
            "Checkpoint 5.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 6: Inspection of bench structural integrity and numbered desk decal stability 6",
            "Checkpoint 6.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 7: Inspection of bench structural integrity and numbered desk decal stability 7",
            "Checkpoint 7.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 8: Inspection of bench structural integrity and numbered desk decal stability 8",
            "Checkpoint 8.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
        ],
    },
    {
        "room_number": "HUM-105",
        "floor": 1,
        "total_area_sqft": 1400,
        "usable_capacity": 36,
        "physical_capacity": 42,
        "grid": {"rows": 6, "columns": 7},
        "cctv_cameras": [
            {"cam_id": "CAM-105-FRONT", "coverage": "Podium & Rows 1-3", "resolution": "4K UHD"},
            {"cam_id": "CAM-105-REAR", "coverage": "Entrance & Rows 4-6", "resolution": "4K UHD"},
        ],
        "accessibility": {"wheelchair_ramp": True, "tactile_path": True, "wide_entrance": True},
        "power_backup": {"ups_inverter": True, "generator_line": True, "battery_runtime_min": 180},
        "inspection_checkpoints": [
            "Checkpoint 1: Inspection of bench structural integrity and numbered desk decal stability 1",
            "Checkpoint 1.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 2: Inspection of bench structural integrity and numbered desk decal stability 2",
            "Checkpoint 2.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 3: Inspection of bench structural integrity and numbered desk decal stability 3",
            "Checkpoint 3.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 4: Inspection of bench structural integrity and numbered desk decal stability 4",
            "Checkpoint 4.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 5: Inspection of bench structural integrity and numbered desk decal stability 5",
            "Checkpoint 5.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 6: Inspection of bench structural integrity and numbered desk decal stability 6",
            "Checkpoint 6.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 7: Inspection of bench structural integrity and numbered desk decal stability 7",
            "Checkpoint 7.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 8: Inspection of bench structural integrity and numbered desk decal stability 8",
            "Checkpoint 8.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
        ],
    },
    {
        "room_number": "HUM-106",
        "floor": 1,
        "total_area_sqft": 1400,
        "usable_capacity": 36,
        "physical_capacity": 42,
        "grid": {"rows": 6, "columns": 7},
        "cctv_cameras": [
            {"cam_id": "CAM-106-FRONT", "coverage": "Podium & Rows 1-3", "resolution": "4K UHD"},
            {"cam_id": "CAM-106-REAR", "coverage": "Entrance & Rows 4-6", "resolution": "4K UHD"},
        ],
        "accessibility": {"wheelchair_ramp": True, "tactile_path": True, "wide_entrance": True},
        "power_backup": {"ups_inverter": True, "generator_line": True, "battery_runtime_min": 180},
        "inspection_checkpoints": [
            "Checkpoint 1: Inspection of bench structural integrity and numbered desk decal stability 1",
            "Checkpoint 1.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 2: Inspection of bench structural integrity and numbered desk decal stability 2",
            "Checkpoint 2.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 3: Inspection of bench structural integrity and numbered desk decal stability 3",
            "Checkpoint 3.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 4: Inspection of bench structural integrity and numbered desk decal stability 4",
            "Checkpoint 4.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 5: Inspection of bench structural integrity and numbered desk decal stability 5",
            "Checkpoint 5.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 6: Inspection of bench structural integrity and numbered desk decal stability 6",
            "Checkpoint 6.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 7: Inspection of bench structural integrity and numbered desk decal stability 7",
            "Checkpoint 7.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 8: Inspection of bench structural integrity and numbered desk decal stability 8",
            "Checkpoint 8.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
        ],
    },
    {
        "room_number": "HUM-107",
        "floor": 1,
        "total_area_sqft": 1400,
        "usable_capacity": 36,
        "physical_capacity": 42,
        "grid": {"rows": 6, "columns": 7},
        "cctv_cameras": [
            {"cam_id": "CAM-107-FRONT", "coverage": "Podium & Rows 1-3", "resolution": "4K UHD"},
            {"cam_id": "CAM-107-REAR", "coverage": "Entrance & Rows 4-6", "resolution": "4K UHD"},
        ],
        "accessibility": {"wheelchair_ramp": True, "tactile_path": True, "wide_entrance": True},
        "power_backup": {"ups_inverter": True, "generator_line": True, "battery_runtime_min": 180},
        "inspection_checkpoints": [
            "Checkpoint 1: Inspection of bench structural integrity and numbered desk decal stability 1",
            "Checkpoint 1.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 2: Inspection of bench structural integrity and numbered desk decal stability 2",
            "Checkpoint 2.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 3: Inspection of bench structural integrity and numbered desk decal stability 3",
            "Checkpoint 3.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 4: Inspection of bench structural integrity and numbered desk decal stability 4",
            "Checkpoint 4.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 5: Inspection of bench structural integrity and numbered desk decal stability 5",
            "Checkpoint 5.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 6: Inspection of bench structural integrity and numbered desk decal stability 6",
            "Checkpoint 6.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 7: Inspection of bench structural integrity and numbered desk decal stability 7",
            "Checkpoint 7.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 8: Inspection of bench structural integrity and numbered desk decal stability 8",
            "Checkpoint 8.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
        ],
    },
    {
        "room_number": "HUM-108",
        "floor": 1,
        "total_area_sqft": 1400,
        "usable_capacity": 36,
        "physical_capacity": 42,
        "grid": {"rows": 6, "columns": 7},
        "cctv_cameras": [
            {"cam_id": "CAM-108-FRONT", "coverage": "Podium & Rows 1-3", "resolution": "4K UHD"},
            {"cam_id": "CAM-108-REAR", "coverage": "Entrance & Rows 4-6", "resolution": "4K UHD"},
        ],
        "accessibility": {"wheelchair_ramp": True, "tactile_path": True, "wide_entrance": True},
        "power_backup": {"ups_inverter": True, "generator_line": True, "battery_runtime_min": 180},
        "inspection_checkpoints": [
            "Checkpoint 1: Inspection of bench structural integrity and numbered desk decal stability 1",
            "Checkpoint 1.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 2: Inspection of bench structural integrity and numbered desk decal stability 2",
            "Checkpoint 2.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 3: Inspection of bench structural integrity and numbered desk decal stability 3",
            "Checkpoint 3.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 4: Inspection of bench structural integrity and numbered desk decal stability 4",
            "Checkpoint 4.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 5: Inspection of bench structural integrity and numbered desk decal stability 5",
            "Checkpoint 5.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 6: Inspection of bench structural integrity and numbered desk decal stability 6",
            "Checkpoint 6.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 7: Inspection of bench structural integrity and numbered desk decal stability 7",
            "Checkpoint 7.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 8: Inspection of bench structural integrity and numbered desk decal stability 8",
            "Checkpoint 8.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
        ],
    },
    {
        "room_number": "HUM-109",
        "floor": 1,
        "total_area_sqft": 1400,
        "usable_capacity": 36,
        "physical_capacity": 42,
        "grid": {"rows": 6, "columns": 7},
        "cctv_cameras": [
            {"cam_id": "CAM-109-FRONT", "coverage": "Podium & Rows 1-3", "resolution": "4K UHD"},
            {"cam_id": "CAM-109-REAR", "coverage": "Entrance & Rows 4-6", "resolution": "4K UHD"},
        ],
        "accessibility": {"wheelchair_ramp": True, "tactile_path": True, "wide_entrance": True},
        "power_backup": {"ups_inverter": True, "generator_line": True, "battery_runtime_min": 180},
        "inspection_checkpoints": [
            "Checkpoint 1: Inspection of bench structural integrity and numbered desk decal stability 1",
            "Checkpoint 1.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 2: Inspection of bench structural integrity and numbered desk decal stability 2",
            "Checkpoint 2.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 3: Inspection of bench structural integrity and numbered desk decal stability 3",
            "Checkpoint 3.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 4: Inspection of bench structural integrity and numbered desk decal stability 4",
            "Checkpoint 4.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 5: Inspection of bench structural integrity and numbered desk decal stability 5",
            "Checkpoint 5.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 6: Inspection of bench structural integrity and numbered desk decal stability 6",
            "Checkpoint 6.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 7: Inspection of bench structural integrity and numbered desk decal stability 7",
            "Checkpoint 7.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 8: Inspection of bench structural integrity and numbered desk decal stability 8",
            "Checkpoint 8.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
        ],
    },
    {
        "room_number": "HUM-110",
        "floor": 1,
        "total_area_sqft": 1400,
        "usable_capacity": 36,
        "physical_capacity": 42,
        "grid": {"rows": 6, "columns": 7},
        "cctv_cameras": [
            {"cam_id": "CAM-110-FRONT", "coverage": "Podium & Rows 1-3", "resolution": "4K UHD"},
            {"cam_id": "CAM-110-REAR", "coverage": "Entrance & Rows 4-6", "resolution": "4K UHD"},
        ],
        "accessibility": {"wheelchair_ramp": True, "tactile_path": True, "wide_entrance": True},
        "power_backup": {"ups_inverter": True, "generator_line": True, "battery_runtime_min": 180},
        "inspection_checkpoints": [
            "Checkpoint 1: Inspection of bench structural integrity and numbered desk decal stability 1",
            "Checkpoint 1.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 2: Inspection of bench structural integrity and numbered desk decal stability 2",
            "Checkpoint 2.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 3: Inspection of bench structural integrity and numbered desk decal stability 3",
            "Checkpoint 3.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 4: Inspection of bench structural integrity and numbered desk decal stability 4",
            "Checkpoint 4.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 5: Inspection of bench structural integrity and numbered desk decal stability 5",
            "Checkpoint 5.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 6: Inspection of bench structural integrity and numbered desk decal stability 6",
            "Checkpoint 6.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 7: Inspection of bench structural integrity and numbered desk decal stability 7",
            "Checkpoint 7.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 8: Inspection of bench structural integrity and numbered desk decal stability 8",
            "Checkpoint 8.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
        ],
    },
    {
        "room_number": "HUM-111",
        "floor": 1,
        "total_area_sqft": 1400,
        "usable_capacity": 36,
        "physical_capacity": 42,
        "grid": {"rows": 6, "columns": 7},
        "cctv_cameras": [
            {"cam_id": "CAM-111-FRONT", "coverage": "Podium & Rows 1-3", "resolution": "4K UHD"},
            {"cam_id": "CAM-111-REAR", "coverage": "Entrance & Rows 4-6", "resolution": "4K UHD"},
        ],
        "accessibility": {"wheelchair_ramp": True, "tactile_path": True, "wide_entrance": True},
        "power_backup": {"ups_inverter": True, "generator_line": True, "battery_runtime_min": 180},
        "inspection_checkpoints": [
            "Checkpoint 1: Inspection of bench structural integrity and numbered desk decal stability 1",
            "Checkpoint 1.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 2: Inspection of bench structural integrity and numbered desk decal stability 2",
            "Checkpoint 2.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 3: Inspection of bench structural integrity and numbered desk decal stability 3",
            "Checkpoint 3.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 4: Inspection of bench structural integrity and numbered desk decal stability 4",
            "Checkpoint 4.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 5: Inspection of bench structural integrity and numbered desk decal stability 5",
            "Checkpoint 5.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 6: Inspection of bench structural integrity and numbered desk decal stability 6",
            "Checkpoint 6.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 7: Inspection of bench structural integrity and numbered desk decal stability 7",
            "Checkpoint 7.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 8: Inspection of bench structural integrity and numbered desk decal stability 8",
            "Checkpoint 8.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
        ],
    },
    {
        "room_number": "HUM-112",
        "floor": 1,
        "total_area_sqft": 1400,
        "usable_capacity": 36,
        "physical_capacity": 42,
        "grid": {"rows": 6, "columns": 7},
        "cctv_cameras": [
            {"cam_id": "CAM-112-FRONT", "coverage": "Podium & Rows 1-3", "resolution": "4K UHD"},
            {"cam_id": "CAM-112-REAR", "coverage": "Entrance & Rows 4-6", "resolution": "4K UHD"},
        ],
        "accessibility": {"wheelchair_ramp": True, "tactile_path": True, "wide_entrance": True},
        "power_backup": {"ups_inverter": True, "generator_line": True, "battery_runtime_min": 180},
        "inspection_checkpoints": [
            "Checkpoint 1: Inspection of bench structural integrity and numbered desk decal stability 1",
            "Checkpoint 1.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 2: Inspection of bench structural integrity and numbered desk decal stability 2",
            "Checkpoint 2.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 3: Inspection of bench structural integrity and numbered desk decal stability 3",
            "Checkpoint 3.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 4: Inspection of bench structural integrity and numbered desk decal stability 4",
            "Checkpoint 4.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 5: Inspection of bench structural integrity and numbered desk decal stability 5",
            "Checkpoint 5.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 6: Inspection of bench structural integrity and numbered desk decal stability 6",
            "Checkpoint 6.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 7: Inspection of bench structural integrity and numbered desk decal stability 7",
            "Checkpoint 7.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 8: Inspection of bench structural integrity and numbered desk decal stability 8",
            "Checkpoint 8.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
        ],
    },
    {
        "room_number": "HUM-113",
        "floor": 1,
        "total_area_sqft": 1400,
        "usable_capacity": 36,
        "physical_capacity": 42,
        "grid": {"rows": 6, "columns": 7},
        "cctv_cameras": [
            {"cam_id": "CAM-113-FRONT", "coverage": "Podium & Rows 1-3", "resolution": "4K UHD"},
            {"cam_id": "CAM-113-REAR", "coverage": "Entrance & Rows 4-6", "resolution": "4K UHD"},
        ],
        "accessibility": {"wheelchair_ramp": True, "tactile_path": True, "wide_entrance": True},
        "power_backup": {"ups_inverter": True, "generator_line": True, "battery_runtime_min": 180},
        "inspection_checkpoints": [
            "Checkpoint 1: Inspection of bench structural integrity and numbered desk decal stability 1",
            "Checkpoint 1.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 2: Inspection of bench structural integrity and numbered desk decal stability 2",
            "Checkpoint 2.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 3: Inspection of bench structural integrity and numbered desk decal stability 3",
            "Checkpoint 3.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 4: Inspection of bench structural integrity and numbered desk decal stability 4",
            "Checkpoint 4.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 5: Inspection of bench structural integrity and numbered desk decal stability 5",
            "Checkpoint 5.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 6: Inspection of bench structural integrity and numbered desk decal stability 6",
            "Checkpoint 6.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 7: Inspection of bench structural integrity and numbered desk decal stability 7",
            "Checkpoint 7.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 8: Inspection of bench structural integrity and numbered desk decal stability 8",
            "Checkpoint 8.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
        ],
    },
    {
        "room_number": "HUM-114",
        "floor": 1,
        "total_area_sqft": 1400,
        "usable_capacity": 36,
        "physical_capacity": 42,
        "grid": {"rows": 6, "columns": 7},
        "cctv_cameras": [
            {"cam_id": "CAM-114-FRONT", "coverage": "Podium & Rows 1-3", "resolution": "4K UHD"},
            {"cam_id": "CAM-114-REAR", "coverage": "Entrance & Rows 4-6", "resolution": "4K UHD"},
        ],
        "accessibility": {"wheelchair_ramp": True, "tactile_path": True, "wide_entrance": True},
        "power_backup": {"ups_inverter": True, "generator_line": True, "battery_runtime_min": 180},
        "inspection_checkpoints": [
            "Checkpoint 1: Inspection of bench structural integrity and numbered desk decal stability 1",
            "Checkpoint 1.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 2: Inspection of bench structural integrity and numbered desk decal stability 2",
            "Checkpoint 2.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 3: Inspection of bench structural integrity and numbered desk decal stability 3",
            "Checkpoint 3.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 4: Inspection of bench structural integrity and numbered desk decal stability 4",
            "Checkpoint 4.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 5: Inspection of bench structural integrity and numbered desk decal stability 5",
            "Checkpoint 5.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 6: Inspection of bench structural integrity and numbered desk decal stability 6",
            "Checkpoint 6.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 7: Inspection of bench structural integrity and numbered desk decal stability 7",
            "Checkpoint 7.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 8: Inspection of bench structural integrity and numbered desk decal stability 8",
            "Checkpoint 8.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
        ],
    },
    {
        "room_number": "HUM-115",
        "floor": 1,
        "total_area_sqft": 1400,
        "usable_capacity": 36,
        "physical_capacity": 42,
        "grid": {"rows": 6, "columns": 7},
        "cctv_cameras": [
            {"cam_id": "CAM-115-FRONT", "coverage": "Podium & Rows 1-3", "resolution": "4K UHD"},
            {"cam_id": "CAM-115-REAR", "coverage": "Entrance & Rows 4-6", "resolution": "4K UHD"},
        ],
        "accessibility": {"wheelchair_ramp": True, "tactile_path": True, "wide_entrance": True},
        "power_backup": {"ups_inverter": True, "generator_line": True, "battery_runtime_min": 180},
        "inspection_checkpoints": [
            "Checkpoint 1: Inspection of bench structural integrity and numbered desk decal stability 1",
            "Checkpoint 1.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 2: Inspection of bench structural integrity and numbered desk decal stability 2",
            "Checkpoint 2.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 3: Inspection of bench structural integrity and numbered desk decal stability 3",
            "Checkpoint 3.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 4: Inspection of bench structural integrity and numbered desk decal stability 4",
            "Checkpoint 4.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 5: Inspection of bench structural integrity and numbered desk decal stability 5",
            "Checkpoint 5.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 6: Inspection of bench structural integrity and numbered desk decal stability 6",
            "Checkpoint 6.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 7: Inspection of bench structural integrity and numbered desk decal stability 7",
            "Checkpoint 7.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 8: Inspection of bench structural integrity and numbered desk decal stability 8",
            "Checkpoint 8.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
        ],
    },
    {
        "room_number": "HUM-116",
        "floor": 1,
        "total_area_sqft": 1400,
        "usable_capacity": 36,
        "physical_capacity": 42,
        "grid": {"rows": 6, "columns": 7},
        "cctv_cameras": [
            {"cam_id": "CAM-116-FRONT", "coverage": "Podium & Rows 1-3", "resolution": "4K UHD"},
            {"cam_id": "CAM-116-REAR", "coverage": "Entrance & Rows 4-6", "resolution": "4K UHD"},
        ],
        "accessibility": {"wheelchair_ramp": True, "tactile_path": True, "wide_entrance": True},
        "power_backup": {"ups_inverter": True, "generator_line": True, "battery_runtime_min": 180},
        "inspection_checkpoints": [
            "Checkpoint 1: Inspection of bench structural integrity and numbered desk decal stability 1",
            "Checkpoint 1.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 2: Inspection of bench structural integrity and numbered desk decal stability 2",
            "Checkpoint 2.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 3: Inspection of bench structural integrity and numbered desk decal stability 3",
            "Checkpoint 3.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 4: Inspection of bench structural integrity and numbered desk decal stability 4",
            "Checkpoint 4.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 5: Inspection of bench structural integrity and numbered desk decal stability 5",
            "Checkpoint 5.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 6: Inspection of bench structural integrity and numbered desk decal stability 6",
            "Checkpoint 6.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 7: Inspection of bench structural integrity and numbered desk decal stability 7",
            "Checkpoint 7.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 8: Inspection of bench structural integrity and numbered desk decal stability 8",
            "Checkpoint 8.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
        ],
    },
    {
        "room_number": "HUM-117",
        "floor": 1,
        "total_area_sqft": 1400,
        "usable_capacity": 36,
        "physical_capacity": 42,
        "grid": {"rows": 6, "columns": 7},
        "cctv_cameras": [
            {"cam_id": "CAM-117-FRONT", "coverage": "Podium & Rows 1-3", "resolution": "4K UHD"},
            {"cam_id": "CAM-117-REAR", "coverage": "Entrance & Rows 4-6", "resolution": "4K UHD"},
        ],
        "accessibility": {"wheelchair_ramp": True, "tactile_path": True, "wide_entrance": True},
        "power_backup": {"ups_inverter": True, "generator_line": True, "battery_runtime_min": 180},
        "inspection_checkpoints": [
            "Checkpoint 1: Inspection of bench structural integrity and numbered desk decal stability 1",
            "Checkpoint 1.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 2: Inspection of bench structural integrity and numbered desk decal stability 2",
            "Checkpoint 2.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 3: Inspection of bench structural integrity and numbered desk decal stability 3",
            "Checkpoint 3.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 4: Inspection of bench structural integrity and numbered desk decal stability 4",
            "Checkpoint 4.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 5: Inspection of bench structural integrity and numbered desk decal stability 5",
            "Checkpoint 5.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 6: Inspection of bench structural integrity and numbered desk decal stability 6",
            "Checkpoint 6.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 7: Inspection of bench structural integrity and numbered desk decal stability 7",
            "Checkpoint 7.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 8: Inspection of bench structural integrity and numbered desk decal stability 8",
            "Checkpoint 8.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
        ],
    },
    {
        "room_number": "HUM-118",
        "floor": 1,
        "total_area_sqft": 1400,
        "usable_capacity": 36,
        "physical_capacity": 42,
        "grid": {"rows": 6, "columns": 7},
        "cctv_cameras": [
            {"cam_id": "CAM-118-FRONT", "coverage": "Podium & Rows 1-3", "resolution": "4K UHD"},
            {"cam_id": "CAM-118-REAR", "coverage": "Entrance & Rows 4-6", "resolution": "4K UHD"},
        ],
        "accessibility": {"wheelchair_ramp": True, "tactile_path": True, "wide_entrance": True},
        "power_backup": {"ups_inverter": True, "generator_line": True, "battery_runtime_min": 180},
        "inspection_checkpoints": [
            "Checkpoint 1: Inspection of bench structural integrity and numbered desk decal stability 1",
            "Checkpoint 1.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 2: Inspection of bench structural integrity and numbered desk decal stability 2",
            "Checkpoint 2.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 3: Inspection of bench structural integrity and numbered desk decal stability 3",
            "Checkpoint 3.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 4: Inspection of bench structural integrity and numbered desk decal stability 4",
            "Checkpoint 4.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 5: Inspection of bench structural integrity and numbered desk decal stability 5",
            "Checkpoint 5.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 6: Inspection of bench structural integrity and numbered desk decal stability 6",
            "Checkpoint 6.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 7: Inspection of bench structural integrity and numbered desk decal stability 7",
            "Checkpoint 7.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 8: Inspection of bench structural integrity and numbered desk decal stability 8",
            "Checkpoint 8.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
        ],
    },
    {
        "room_number": "HUM-119",
        "floor": 1,
        "total_area_sqft": 1400,
        "usable_capacity": 36,
        "physical_capacity": 42,
        "grid": {"rows": 6, "columns": 7},
        "cctv_cameras": [
            {"cam_id": "CAM-119-FRONT", "coverage": "Podium & Rows 1-3", "resolution": "4K UHD"},
            {"cam_id": "CAM-119-REAR", "coverage": "Entrance & Rows 4-6", "resolution": "4K UHD"},
        ],
        "accessibility": {"wheelchair_ramp": True, "tactile_path": True, "wide_entrance": True},
        "power_backup": {"ups_inverter": True, "generator_line": True, "battery_runtime_min": 180},
        "inspection_checkpoints": [
            "Checkpoint 1: Inspection of bench structural integrity and numbered desk decal stability 1",
            "Checkpoint 1.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 2: Inspection of bench structural integrity and numbered desk decal stability 2",
            "Checkpoint 2.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 3: Inspection of bench structural integrity and numbered desk decal stability 3",
            "Checkpoint 3.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 4: Inspection of bench structural integrity and numbered desk decal stability 4",
            "Checkpoint 4.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 5: Inspection of bench structural integrity and numbered desk decal stability 5",
            "Checkpoint 5.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 6: Inspection of bench structural integrity and numbered desk decal stability 6",
            "Checkpoint 6.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 7: Inspection of bench structural integrity and numbered desk decal stability 7",
            "Checkpoint 7.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 8: Inspection of bench structural integrity and numbered desk decal stability 8",
            "Checkpoint 8.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
        ],
    },
    {
        "room_number": "HUM-120",
        "floor": 1,
        "total_area_sqft": 1400,
        "usable_capacity": 36,
        "physical_capacity": 42,
        "grid": {"rows": 6, "columns": 7},
        "cctv_cameras": [
            {"cam_id": "CAM-120-FRONT", "coverage": "Podium & Rows 1-3", "resolution": "4K UHD"},
            {"cam_id": "CAM-120-REAR", "coverage": "Entrance & Rows 4-6", "resolution": "4K UHD"},
        ],
        "accessibility": {"wheelchair_ramp": True, "tactile_path": True, "wide_entrance": True},
        "power_backup": {"ups_inverter": True, "generator_line": True, "battery_runtime_min": 180},
        "inspection_checkpoints": [
            "Checkpoint 1: Inspection of bench structural integrity and numbered desk decal stability 1",
            "Checkpoint 1.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 2: Inspection of bench structural integrity and numbered desk decal stability 2",
            "Checkpoint 2.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 3: Inspection of bench structural integrity and numbered desk decal stability 3",
            "Checkpoint 3.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 4: Inspection of bench structural integrity and numbered desk decal stability 4",
            "Checkpoint 4.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 5: Inspection of bench structural integrity and numbered desk decal stability 5",
            "Checkpoint 5.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 6: Inspection of bench structural integrity and numbered desk decal stability 6",
            "Checkpoint 6.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 7: Inspection of bench structural integrity and numbered desk decal stability 7",
            "Checkpoint 7.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 8: Inspection of bench structural integrity and numbered desk decal stability 8",
            "Checkpoint 8.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
        ],
    },
    {
        "room_number": "HUM-121",
        "floor": 1,
        "total_area_sqft": 1400,
        "usable_capacity": 36,
        "physical_capacity": 42,
        "grid": {"rows": 6, "columns": 7},
        "cctv_cameras": [
            {"cam_id": "CAM-121-FRONT", "coverage": "Podium & Rows 1-3", "resolution": "4K UHD"},
            {"cam_id": "CAM-121-REAR", "coverage": "Entrance & Rows 4-6", "resolution": "4K UHD"},
        ],
        "accessibility": {"wheelchair_ramp": True, "tactile_path": True, "wide_entrance": True},
        "power_backup": {"ups_inverter": True, "generator_line": True, "battery_runtime_min": 180},
        "inspection_checkpoints": [
            "Checkpoint 1: Inspection of bench structural integrity and numbered desk decal stability 1",
            "Checkpoint 1.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 2: Inspection of bench structural integrity and numbered desk decal stability 2",
            "Checkpoint 2.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 3: Inspection of bench structural integrity and numbered desk decal stability 3",
            "Checkpoint 3.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 4: Inspection of bench structural integrity and numbered desk decal stability 4",
            "Checkpoint 4.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 5: Inspection of bench structural integrity and numbered desk decal stability 5",
            "Checkpoint 5.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 6: Inspection of bench structural integrity and numbered desk decal stability 6",
            "Checkpoint 6.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 7: Inspection of bench structural integrity and numbered desk decal stability 7",
            "Checkpoint 7.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 8: Inspection of bench structural integrity and numbered desk decal stability 8",
            "Checkpoint 8.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
        ],
    },
    {
        "room_number": "HUM-122",
        "floor": 1,
        "total_area_sqft": 1400,
        "usable_capacity": 36,
        "physical_capacity": 42,
        "grid": {"rows": 6, "columns": 7},
        "cctv_cameras": [
            {"cam_id": "CAM-122-FRONT", "coverage": "Podium & Rows 1-3", "resolution": "4K UHD"},
            {"cam_id": "CAM-122-REAR", "coverage": "Entrance & Rows 4-6", "resolution": "4K UHD"},
        ],
        "accessibility": {"wheelchair_ramp": True, "tactile_path": True, "wide_entrance": True},
        "power_backup": {"ups_inverter": True, "generator_line": True, "battery_runtime_min": 180},
        "inspection_checkpoints": [
            "Checkpoint 1: Inspection of bench structural integrity and numbered desk decal stability 1",
            "Checkpoint 1.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 2: Inspection of bench structural integrity and numbered desk decal stability 2",
            "Checkpoint 2.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 3: Inspection of bench structural integrity and numbered desk decal stability 3",
            "Checkpoint 3.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 4: Inspection of bench structural integrity and numbered desk decal stability 4",
            "Checkpoint 4.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 5: Inspection of bench structural integrity and numbered desk decal stability 5",
            "Checkpoint 5.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 6: Inspection of bench structural integrity and numbered desk decal stability 6",
            "Checkpoint 6.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 7: Inspection of bench structural integrity and numbered desk decal stability 7",
            "Checkpoint 7.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 8: Inspection of bench structural integrity and numbered desk decal stability 8",
            "Checkpoint 8.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
        ],
    },
    {
        "room_number": "HUM-123",
        "floor": 1,
        "total_area_sqft": 1400,
        "usable_capacity": 36,
        "physical_capacity": 42,
        "grid": {"rows": 6, "columns": 7},
        "cctv_cameras": [
            {"cam_id": "CAM-123-FRONT", "coverage": "Podium & Rows 1-3", "resolution": "4K UHD"},
            {"cam_id": "CAM-123-REAR", "coverage": "Entrance & Rows 4-6", "resolution": "4K UHD"},
        ],
        "accessibility": {"wheelchair_ramp": True, "tactile_path": True, "wide_entrance": True},
        "power_backup": {"ups_inverter": True, "generator_line": True, "battery_runtime_min": 180},
        "inspection_checkpoints": [
            "Checkpoint 1: Inspection of bench structural integrity and numbered desk decal stability 1",
            "Checkpoint 1.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 2: Inspection of bench structural integrity and numbered desk decal stability 2",
            "Checkpoint 2.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 3: Inspection of bench structural integrity and numbered desk decal stability 3",
            "Checkpoint 3.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 4: Inspection of bench structural integrity and numbered desk decal stability 4",
            "Checkpoint 4.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 5: Inspection of bench structural integrity and numbered desk decal stability 5",
            "Checkpoint 5.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 6: Inspection of bench structural integrity and numbered desk decal stability 6",
            "Checkpoint 6.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 7: Inspection of bench structural integrity and numbered desk decal stability 7",
            "Checkpoint 7.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 8: Inspection of bench structural integrity and numbered desk decal stability 8",
            "Checkpoint 8.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
        ],
    },
    {
        "room_number": "HUM-124",
        "floor": 1,
        "total_area_sqft": 1400,
        "usable_capacity": 36,
        "physical_capacity": 42,
        "grid": {"rows": 6, "columns": 7},
        "cctv_cameras": [
            {"cam_id": "CAM-124-FRONT", "coverage": "Podium & Rows 1-3", "resolution": "4K UHD"},
            {"cam_id": "CAM-124-REAR", "coverage": "Entrance & Rows 4-6", "resolution": "4K UHD"},
        ],
        "accessibility": {"wheelchair_ramp": True, "tactile_path": True, "wide_entrance": True},
        "power_backup": {"ups_inverter": True, "generator_line": True, "battery_runtime_min": 180},
        "inspection_checkpoints": [
            "Checkpoint 1: Inspection of bench structural integrity and numbered desk decal stability 1",
            "Checkpoint 1.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 2: Inspection of bench structural integrity and numbered desk decal stability 2",
            "Checkpoint 2.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 3: Inspection of bench structural integrity and numbered desk decal stability 3",
            "Checkpoint 3.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 4: Inspection of bench structural integrity and numbered desk decal stability 4",
            "Checkpoint 4.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 5: Inspection of bench structural integrity and numbered desk decal stability 5",
            "Checkpoint 5.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 6: Inspection of bench structural integrity and numbered desk decal stability 6",
            "Checkpoint 6.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 7: Inspection of bench structural integrity and numbered desk decal stability 7",
            "Checkpoint 7.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 8: Inspection of bench structural integrity and numbered desk decal stability 8",
            "Checkpoint 8.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
        ],
    },
    {
        "room_number": "HUM-125",
        "floor": 1,
        "total_area_sqft": 1400,
        "usable_capacity": 36,
        "physical_capacity": 42,
        "grid": {"rows": 6, "columns": 7},
        "cctv_cameras": [
            {"cam_id": "CAM-125-FRONT", "coverage": "Podium & Rows 1-3", "resolution": "4K UHD"},
            {"cam_id": "CAM-125-REAR", "coverage": "Entrance & Rows 4-6", "resolution": "4K UHD"},
        ],
        "accessibility": {"wheelchair_ramp": True, "tactile_path": True, "wide_entrance": True},
        "power_backup": {"ups_inverter": True, "generator_line": True, "battery_runtime_min": 180},
        "inspection_checkpoints": [
            "Checkpoint 1: Inspection of bench structural integrity and numbered desk decal stability 1",
            "Checkpoint 1.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 2: Inspection of bench structural integrity and numbered desk decal stability 2",
            "Checkpoint 2.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 3: Inspection of bench structural integrity and numbered desk decal stability 3",
            "Checkpoint 3.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 4: Inspection of bench structural integrity and numbered desk decal stability 4",
            "Checkpoint 4.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 5: Inspection of bench structural integrity and numbered desk decal stability 5",
            "Checkpoint 5.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 6: Inspection of bench structural integrity and numbered desk decal stability 6",
            "Checkpoint 6.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 7: Inspection of bench structural integrity and numbered desk decal stability 7",
            "Checkpoint 7.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 8: Inspection of bench structural integrity and numbered desk decal stability 8",
            "Checkpoint 8.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
        ],
    },
    {
        "room_number": "HUM-126",
        "floor": 1,
        "total_area_sqft": 1400,
        "usable_capacity": 36,
        "physical_capacity": 42,
        "grid": {"rows": 6, "columns": 7},
        "cctv_cameras": [
            {"cam_id": "CAM-126-FRONT", "coverage": "Podium & Rows 1-3", "resolution": "4K UHD"},
            {"cam_id": "CAM-126-REAR", "coverage": "Entrance & Rows 4-6", "resolution": "4K UHD"},
        ],
        "accessibility": {"wheelchair_ramp": True, "tactile_path": True, "wide_entrance": True},
        "power_backup": {"ups_inverter": True, "generator_line": True, "battery_runtime_min": 180},
        "inspection_checkpoints": [
            "Checkpoint 1: Inspection of bench structural integrity and numbered desk decal stability 1",
            "Checkpoint 1.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 2: Inspection of bench structural integrity and numbered desk decal stability 2",
            "Checkpoint 2.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 3: Inspection of bench structural integrity and numbered desk decal stability 3",
            "Checkpoint 3.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 4: Inspection of bench structural integrity and numbered desk decal stability 4",
            "Checkpoint 4.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 5: Inspection of bench structural integrity and numbered desk decal stability 5",
            "Checkpoint 5.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 6: Inspection of bench structural integrity and numbered desk decal stability 6",
            "Checkpoint 6.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 7: Inspection of bench structural integrity and numbered desk decal stability 7",
            "Checkpoint 7.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 8: Inspection of bench structural integrity and numbered desk decal stability 8",
            "Checkpoint 8.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
        ],
    },
    {
        "room_number": "HUM-127",
        "floor": 1,
        "total_area_sqft": 1400,
        "usable_capacity": 36,
        "physical_capacity": 42,
        "grid": {"rows": 6, "columns": 7},
        "cctv_cameras": [
            {"cam_id": "CAM-127-FRONT", "coverage": "Podium & Rows 1-3", "resolution": "4K UHD"},
            {"cam_id": "CAM-127-REAR", "coverage": "Entrance & Rows 4-6", "resolution": "4K UHD"},
        ],
        "accessibility": {"wheelchair_ramp": True, "tactile_path": True, "wide_entrance": True},
        "power_backup": {"ups_inverter": True, "generator_line": True, "battery_runtime_min": 180},
        "inspection_checkpoints": [
            "Checkpoint 1: Inspection of bench structural integrity and numbered desk decal stability 1",
            "Checkpoint 1.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 2: Inspection of bench structural integrity and numbered desk decal stability 2",
            "Checkpoint 2.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 3: Inspection of bench structural integrity and numbered desk decal stability 3",
            "Checkpoint 3.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 4: Inspection of bench structural integrity and numbered desk decal stability 4",
            "Checkpoint 4.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 5: Inspection of bench structural integrity and numbered desk decal stability 5",
            "Checkpoint 5.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 6: Inspection of bench structural integrity and numbered desk decal stability 6",
            "Checkpoint 6.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 7: Inspection of bench structural integrity and numbered desk decal stability 7",
            "Checkpoint 7.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 8: Inspection of bench structural integrity and numbered desk decal stability 8",
            "Checkpoint 8.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
        ],
    },
    {
        "room_number": "HUM-128",
        "floor": 1,
        "total_area_sqft": 1400,
        "usable_capacity": 36,
        "physical_capacity": 42,
        "grid": {"rows": 6, "columns": 7},
        "cctv_cameras": [
            {"cam_id": "CAM-128-FRONT", "coverage": "Podium & Rows 1-3", "resolution": "4K UHD"},
            {"cam_id": "CAM-128-REAR", "coverage": "Entrance & Rows 4-6", "resolution": "4K UHD"},
        ],
        "accessibility": {"wheelchair_ramp": True, "tactile_path": True, "wide_entrance": True},
        "power_backup": {"ups_inverter": True, "generator_line": True, "battery_runtime_min": 180},
        "inspection_checkpoints": [
            "Checkpoint 1: Inspection of bench structural integrity and numbered desk decal stability 1",
            "Checkpoint 1.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 2: Inspection of bench structural integrity and numbered desk decal stability 2",
            "Checkpoint 2.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 3: Inspection of bench structural integrity and numbered desk decal stability 3",
            "Checkpoint 3.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 4: Inspection of bench structural integrity and numbered desk decal stability 4",
            "Checkpoint 4.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 5: Inspection of bench structural integrity and numbered desk decal stability 5",
            "Checkpoint 5.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 6: Inspection of bench structural integrity and numbered desk decal stability 6",
            "Checkpoint 6.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 7: Inspection of bench structural integrity and numbered desk decal stability 7",
            "Checkpoint 7.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 8: Inspection of bench structural integrity and numbered desk decal stability 8",
            "Checkpoint 8.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
        ],
    },
    {
        "room_number": "HUM-129",
        "floor": 1,
        "total_area_sqft": 1400,
        "usable_capacity": 36,
        "physical_capacity": 42,
        "grid": {"rows": 6, "columns": 7},
        "cctv_cameras": [
            {"cam_id": "CAM-129-FRONT", "coverage": "Podium & Rows 1-3", "resolution": "4K UHD"},
            {"cam_id": "CAM-129-REAR", "coverage": "Entrance & Rows 4-6", "resolution": "4K UHD"},
        ],
        "accessibility": {"wheelchair_ramp": True, "tactile_path": True, "wide_entrance": True},
        "power_backup": {"ups_inverter": True, "generator_line": True, "battery_runtime_min": 180},
        "inspection_checkpoints": [
            "Checkpoint 1: Inspection of bench structural integrity and numbered desk decal stability 1",
            "Checkpoint 1.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 2: Inspection of bench structural integrity and numbered desk decal stability 2",
            "Checkpoint 2.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 3: Inspection of bench structural integrity and numbered desk decal stability 3",
            "Checkpoint 3.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 4: Inspection of bench structural integrity and numbered desk decal stability 4",
            "Checkpoint 4.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 5: Inspection of bench structural integrity and numbered desk decal stability 5",
            "Checkpoint 5.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 6: Inspection of bench structural integrity and numbered desk decal stability 6",
            "Checkpoint 6.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 7: Inspection of bench structural integrity and numbered desk decal stability 7",
            "Checkpoint 7.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 8: Inspection of bench structural integrity and numbered desk decal stability 8",
            "Checkpoint 8.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
        ],
    },
    {
        "room_number": "HUM-130",
        "floor": 1,
        "total_area_sqft": 1400,
        "usable_capacity": 36,
        "physical_capacity": 42,
        "grid": {"rows": 6, "columns": 7},
        "cctv_cameras": [
            {"cam_id": "CAM-130-FRONT", "coverage": "Podium & Rows 1-3", "resolution": "4K UHD"},
            {"cam_id": "CAM-130-REAR", "coverage": "Entrance & Rows 4-6", "resolution": "4K UHD"},
        ],
        "accessibility": {"wheelchair_ramp": True, "tactile_path": True, "wide_entrance": True},
        "power_backup": {"ups_inverter": True, "generator_line": True, "battery_runtime_min": 180},
        "inspection_checkpoints": [
            "Checkpoint 1: Inspection of bench structural integrity and numbered desk decal stability 1",
            "Checkpoint 1.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 2: Inspection of bench structural integrity and numbered desk decal stability 2",
            "Checkpoint 2.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 3: Inspection of bench structural integrity and numbered desk decal stability 3",
            "Checkpoint 3.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 4: Inspection of bench structural integrity and numbered desk decal stability 4",
            "Checkpoint 4.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 5: Inspection of bench structural integrity and numbered desk decal stability 5",
            "Checkpoint 5.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 6: Inspection of bench structural integrity and numbered desk decal stability 6",
            "Checkpoint 6.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 7: Inspection of bench structural integrity and numbered desk decal stability 7",
            "Checkpoint 7.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 8: Inspection of bench structural integrity and numbered desk decal stability 8",
            "Checkpoint 8.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
        ],
    },
    {
        "room_number": "HUM-131",
        "floor": 1,
        "total_area_sqft": 1400,
        "usable_capacity": 36,
        "physical_capacity": 42,
        "grid": {"rows": 6, "columns": 7},
        "cctv_cameras": [
            {"cam_id": "CAM-131-FRONT", "coverage": "Podium & Rows 1-3", "resolution": "4K UHD"},
            {"cam_id": "CAM-131-REAR", "coverage": "Entrance & Rows 4-6", "resolution": "4K UHD"},
        ],
        "accessibility": {"wheelchair_ramp": True, "tactile_path": True, "wide_entrance": True},
        "power_backup": {"ups_inverter": True, "generator_line": True, "battery_runtime_min": 180},
        "inspection_checkpoints": [
            "Checkpoint 1: Inspection of bench structural integrity and numbered desk decal stability 1",
            "Checkpoint 1.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 2: Inspection of bench structural integrity and numbered desk decal stability 2",
            "Checkpoint 2.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 3: Inspection of bench structural integrity and numbered desk decal stability 3",
            "Checkpoint 3.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 4: Inspection of bench structural integrity and numbered desk decal stability 4",
            "Checkpoint 4.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 5: Inspection of bench structural integrity and numbered desk decal stability 5",
            "Checkpoint 5.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 6: Inspection of bench structural integrity and numbered desk decal stability 6",
            "Checkpoint 6.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 7: Inspection of bench structural integrity and numbered desk decal stability 7",
            "Checkpoint 7.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 8: Inspection of bench structural integrity and numbered desk decal stability 8",
            "Checkpoint 8.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
        ],
    },
    {
        "room_number": "HUM-132",
        "floor": 1,
        "total_area_sqft": 1400,
        "usable_capacity": 36,
        "physical_capacity": 42,
        "grid": {"rows": 6, "columns": 7},
        "cctv_cameras": [
            {"cam_id": "CAM-132-FRONT", "coverage": "Podium & Rows 1-3", "resolution": "4K UHD"},
            {"cam_id": "CAM-132-REAR", "coverage": "Entrance & Rows 4-6", "resolution": "4K UHD"},
        ],
        "accessibility": {"wheelchair_ramp": True, "tactile_path": True, "wide_entrance": True},
        "power_backup": {"ups_inverter": True, "generator_line": True, "battery_runtime_min": 180},
        "inspection_checkpoints": [
            "Checkpoint 1: Inspection of bench structural integrity and numbered desk decal stability 1",
            "Checkpoint 1.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 2: Inspection of bench structural integrity and numbered desk decal stability 2",
            "Checkpoint 2.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 3: Inspection of bench structural integrity and numbered desk decal stability 3",
            "Checkpoint 3.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 4: Inspection of bench structural integrity and numbered desk decal stability 4",
            "Checkpoint 4.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 5: Inspection of bench structural integrity and numbered desk decal stability 5",
            "Checkpoint 5.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 6: Inspection of bench structural integrity and numbered desk decal stability 6",
            "Checkpoint 6.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 7: Inspection of bench structural integrity and numbered desk decal stability 7",
            "Checkpoint 7.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 8: Inspection of bench structural integrity and numbered desk decal stability 8",
            "Checkpoint 8.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
        ],
    },
    {
        "room_number": "HUM-133",
        "floor": 1,
        "total_area_sqft": 1400,
        "usable_capacity": 36,
        "physical_capacity": 42,
        "grid": {"rows": 6, "columns": 7},
        "cctv_cameras": [
            {"cam_id": "CAM-133-FRONT", "coverage": "Podium & Rows 1-3", "resolution": "4K UHD"},
            {"cam_id": "CAM-133-REAR", "coverage": "Entrance & Rows 4-6", "resolution": "4K UHD"},
        ],
        "accessibility": {"wheelchair_ramp": True, "tactile_path": True, "wide_entrance": True},
        "power_backup": {"ups_inverter": True, "generator_line": True, "battery_runtime_min": 180},
        "inspection_checkpoints": [
            "Checkpoint 1: Inspection of bench structural integrity and numbered desk decal stability 1",
            "Checkpoint 1.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 2: Inspection of bench structural integrity and numbered desk decal stability 2",
            "Checkpoint 2.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 3: Inspection of bench structural integrity and numbered desk decal stability 3",
            "Checkpoint 3.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 4: Inspection of bench structural integrity and numbered desk decal stability 4",
            "Checkpoint 4.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 5: Inspection of bench structural integrity and numbered desk decal stability 5",
            "Checkpoint 5.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 6: Inspection of bench structural integrity and numbered desk decal stability 6",
            "Checkpoint 6.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 7: Inspection of bench structural integrity and numbered desk decal stability 7",
            "Checkpoint 7.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 8: Inspection of bench structural integrity and numbered desk decal stability 8",
            "Checkpoint 8.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
        ],
    },
    {
        "room_number": "HUM-134",
        "floor": 1,
        "total_area_sqft": 1400,
        "usable_capacity": 36,
        "physical_capacity": 42,
        "grid": {"rows": 6, "columns": 7},
        "cctv_cameras": [
            {"cam_id": "CAM-134-FRONT", "coverage": "Podium & Rows 1-3", "resolution": "4K UHD"},
            {"cam_id": "CAM-134-REAR", "coverage": "Entrance & Rows 4-6", "resolution": "4K UHD"},
        ],
        "accessibility": {"wheelchair_ramp": True, "tactile_path": True, "wide_entrance": True},
        "power_backup": {"ups_inverter": True, "generator_line": True, "battery_runtime_min": 180},
        "inspection_checkpoints": [
            "Checkpoint 1: Inspection of bench structural integrity and numbered desk decal stability 1",
            "Checkpoint 1.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 2: Inspection of bench structural integrity and numbered desk decal stability 2",
            "Checkpoint 2.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 3: Inspection of bench structural integrity and numbered desk decal stability 3",
            "Checkpoint 3.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 4: Inspection of bench structural integrity and numbered desk decal stability 4",
            "Checkpoint 4.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 5: Inspection of bench structural integrity and numbered desk decal stability 5",
            "Checkpoint 5.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 6: Inspection of bench structural integrity and numbered desk decal stability 6",
            "Checkpoint 6.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 7: Inspection of bench structural integrity and numbered desk decal stability 7",
            "Checkpoint 7.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 8: Inspection of bench structural integrity and numbered desk decal stability 8",
            "Checkpoint 8.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
        ],
    },
    {
        "room_number": "HUM-135",
        "floor": 1,
        "total_area_sqft": 1400,
        "usable_capacity": 36,
        "physical_capacity": 42,
        "grid": {"rows": 6, "columns": 7},
        "cctv_cameras": [
            {"cam_id": "CAM-135-FRONT", "coverage": "Podium & Rows 1-3", "resolution": "4K UHD"},
            {"cam_id": "CAM-135-REAR", "coverage": "Entrance & Rows 4-6", "resolution": "4K UHD"},
        ],
        "accessibility": {"wheelchair_ramp": True, "tactile_path": True, "wide_entrance": True},
        "power_backup": {"ups_inverter": True, "generator_line": True, "battery_runtime_min": 180},
        "inspection_checkpoints": [
            "Checkpoint 1: Inspection of bench structural integrity and numbered desk decal stability 1",
            "Checkpoint 1.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 2: Inspection of bench structural integrity and numbered desk decal stability 2",
            "Checkpoint 2.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 3: Inspection of bench structural integrity and numbered desk decal stability 3",
            "Checkpoint 3.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 4: Inspection of bench structural integrity and numbered desk decal stability 4",
            "Checkpoint 4.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 5: Inspection of bench structural integrity and numbered desk decal stability 5",
            "Checkpoint 5.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 6: Inspection of bench structural integrity and numbered desk decal stability 6",
            "Checkpoint 6.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 7: Inspection of bench structural integrity and numbered desk decal stability 7",
            "Checkpoint 7.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 8: Inspection of bench structural integrity and numbered desk decal stability 8",
            "Checkpoint 8.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
        ],
    },
    {
        "room_number": "HUM-136",
        "floor": 1,
        "total_area_sqft": 1400,
        "usable_capacity": 36,
        "physical_capacity": 42,
        "grid": {"rows": 6, "columns": 7},
        "cctv_cameras": [
            {"cam_id": "CAM-136-FRONT", "coverage": "Podium & Rows 1-3", "resolution": "4K UHD"},
            {"cam_id": "CAM-136-REAR", "coverage": "Entrance & Rows 4-6", "resolution": "4K UHD"},
        ],
        "accessibility": {"wheelchair_ramp": True, "tactile_path": True, "wide_entrance": True},
        "power_backup": {"ups_inverter": True, "generator_line": True, "battery_runtime_min": 180},
        "inspection_checkpoints": [
            "Checkpoint 1: Inspection of bench structural integrity and numbered desk decal stability 1",
            "Checkpoint 1.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 2: Inspection of bench structural integrity and numbered desk decal stability 2",
            "Checkpoint 2.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 3: Inspection of bench structural integrity and numbered desk decal stability 3",
            "Checkpoint 3.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 4: Inspection of bench structural integrity and numbered desk decal stability 4",
            "Checkpoint 4.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 5: Inspection of bench structural integrity and numbered desk decal stability 5",
            "Checkpoint 5.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 6: Inspection of bench structural integrity and numbered desk decal stability 6",
            "Checkpoint 6.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 7: Inspection of bench structural integrity and numbered desk decal stability 7",
            "Checkpoint 7.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 8: Inspection of bench structural integrity and numbered desk decal stability 8",
            "Checkpoint 8.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
        ],
    },
    {
        "room_number": "HUM-137",
        "floor": 1,
        "total_area_sqft": 1400,
        "usable_capacity": 36,
        "physical_capacity": 42,
        "grid": {"rows": 6, "columns": 7},
        "cctv_cameras": [
            {"cam_id": "CAM-137-FRONT", "coverage": "Podium & Rows 1-3", "resolution": "4K UHD"},
            {"cam_id": "CAM-137-REAR", "coverage": "Entrance & Rows 4-6", "resolution": "4K UHD"},
        ],
        "accessibility": {"wheelchair_ramp": True, "tactile_path": True, "wide_entrance": True},
        "power_backup": {"ups_inverter": True, "generator_line": True, "battery_runtime_min": 180},
        "inspection_checkpoints": [
            "Checkpoint 1: Inspection of bench structural integrity and numbered desk decal stability 1",
            "Checkpoint 1.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 2: Inspection of bench structural integrity and numbered desk decal stability 2",
            "Checkpoint 2.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 3: Inspection of bench structural integrity and numbered desk decal stability 3",
            "Checkpoint 3.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 4: Inspection of bench structural integrity and numbered desk decal stability 4",
            "Checkpoint 4.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 5: Inspection of bench structural integrity and numbered desk decal stability 5",
            "Checkpoint 5.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 6: Inspection of bench structural integrity and numbered desk decal stability 6",
            "Checkpoint 6.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 7: Inspection of bench structural integrity and numbered desk decal stability 7",
            "Checkpoint 7.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 8: Inspection of bench structural integrity and numbered desk decal stability 8",
            "Checkpoint 8.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
        ],
    },
    {
        "room_number": "HUM-138",
        "floor": 1,
        "total_area_sqft": 1400,
        "usable_capacity": 36,
        "physical_capacity": 42,
        "grid": {"rows": 6, "columns": 7},
        "cctv_cameras": [
            {"cam_id": "CAM-138-FRONT", "coverage": "Podium & Rows 1-3", "resolution": "4K UHD"},
            {"cam_id": "CAM-138-REAR", "coverage": "Entrance & Rows 4-6", "resolution": "4K UHD"},
        ],
        "accessibility": {"wheelchair_ramp": True, "tactile_path": True, "wide_entrance": True},
        "power_backup": {"ups_inverter": True, "generator_line": True, "battery_runtime_min": 180},
        "inspection_checkpoints": [
            "Checkpoint 1: Inspection of bench structural integrity and numbered desk decal stability 1",
            "Checkpoint 1.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 2: Inspection of bench structural integrity and numbered desk decal stability 2",
            "Checkpoint 2.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 3: Inspection of bench structural integrity and numbered desk decal stability 3",
            "Checkpoint 3.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 4: Inspection of bench structural integrity and numbered desk decal stability 4",
            "Checkpoint 4.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 5: Inspection of bench structural integrity and numbered desk decal stability 5",
            "Checkpoint 5.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 6: Inspection of bench structural integrity and numbered desk decal stability 6",
            "Checkpoint 6.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 7: Inspection of bench structural integrity and numbered desk decal stability 7",
            "Checkpoint 7.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 8: Inspection of bench structural integrity and numbered desk decal stability 8",
            "Checkpoint 8.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
        ],
    },
    {
        "room_number": "HUM-139",
        "floor": 1,
        "total_area_sqft": 1400,
        "usable_capacity": 36,
        "physical_capacity": 42,
        "grid": {"rows": 6, "columns": 7},
        "cctv_cameras": [
            {"cam_id": "CAM-139-FRONT", "coverage": "Podium & Rows 1-3", "resolution": "4K UHD"},
            {"cam_id": "CAM-139-REAR", "coverage": "Entrance & Rows 4-6", "resolution": "4K UHD"},
        ],
        "accessibility": {"wheelchair_ramp": True, "tactile_path": True, "wide_entrance": True},
        "power_backup": {"ups_inverter": True, "generator_line": True, "battery_runtime_min": 180},
        "inspection_checkpoints": [
            "Checkpoint 1: Inspection of bench structural integrity and numbered desk decal stability 1",
            "Checkpoint 1.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 2: Inspection of bench structural integrity and numbered desk decal stability 2",
            "Checkpoint 2.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 3: Inspection of bench structural integrity and numbered desk decal stability 3",
            "Checkpoint 3.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 4: Inspection of bench structural integrity and numbered desk decal stability 4",
            "Checkpoint 4.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 5: Inspection of bench structural integrity and numbered desk decal stability 5",
            "Checkpoint 5.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 6: Inspection of bench structural integrity and numbered desk decal stability 6",
            "Checkpoint 6.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 7: Inspection of bench structural integrity and numbered desk decal stability 7",
            "Checkpoint 7.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 8: Inspection of bench structural integrity and numbered desk decal stability 8",
            "Checkpoint 8.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
        ],
    },
    {
        "room_number": "HUM-140",
        "floor": 1,
        "total_area_sqft": 1400,
        "usable_capacity": 36,
        "physical_capacity": 42,
        "grid": {"rows": 6, "columns": 7},
        "cctv_cameras": [
            {"cam_id": "CAM-140-FRONT", "coverage": "Podium & Rows 1-3", "resolution": "4K UHD"},
            {"cam_id": "CAM-140-REAR", "coverage": "Entrance & Rows 4-6", "resolution": "4K UHD"},
        ],
        "accessibility": {"wheelchair_ramp": True, "tactile_path": True, "wide_entrance": True},
        "power_backup": {"ups_inverter": True, "generator_line": True, "battery_runtime_min": 180},
        "inspection_checkpoints": [
            "Checkpoint 1: Inspection of bench structural integrity and numbered desk decal stability 1",
            "Checkpoint 1.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 2: Inspection of bench structural integrity and numbered desk decal stability 2",
            "Checkpoint 2.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 3: Inspection of bench structural integrity and numbered desk decal stability 3",
            "Checkpoint 3.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 4: Inspection of bench structural integrity and numbered desk decal stability 4",
            "Checkpoint 4.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 5: Inspection of bench structural integrity and numbered desk decal stability 5",
            "Checkpoint 5.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 6: Inspection of bench structural integrity and numbered desk decal stability 6",
            "Checkpoint 6.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 7: Inspection of bench structural integrity and numbered desk decal stability 7",
            "Checkpoint 7.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
            "Checkpoint 8: Inspection of bench structural integrity and numbered desk decal stability 8",
            "Checkpoint 8.b: Testing illumination level across all desk coordinates exceeding 500 lux benchmark",
        ],
    },
]

def get_complex_total_capacity():
    return sum(r["usable_capacity"] for r in ROOM_SPECIFICATIONS)
