# Generated by Django 5.1.15 on 2026-10-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(default='ExamForge University', max_length=200)),
                ('institution_code', models.CharField(default='EFU-TECH', max_length=30)),
                ('academic_year', models.CharField(default='2025-2026', max_length=20)),
                ('current_term', models.CharField(default='EVEN', max_length=10)),
                ('contact_email', models.EmailField(default='coe@examforge.edu', max_length=254)),
                ('contact_phone', models.CharField(default='+91 98765 43210', max_length=20)),
                ('address', models.TextField(default='Knowledge Park, Higher Education Complex, Hyderabad, India')),
                ('min_attendance_threshold', models.IntegerField(default=75)),
                ('default_exam_duration_mins', models.IntegerField(default=180)),
                ('default_spacing_rule', models.CharField(default='ALTERNATE_COLS', max_length=50)),
                ('hall_ticket_instructions', models.TextField(default='1. Carry this Hall Ticket and ID card.\n2. Arrive 20 mins early.\n3. Electronic gadgets strictly prohibited.\n4. Comply with all invigilator instructions.')),
                ('malpractice_policy', models.TextField(default='Any malpractice or possession of unapproved notes will lead to debarment from the examination and disciplinary hearing.')),
                ('enable_audit_logging', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
