# Generated by Django 6.1.2 on 2026-10-09 09:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID for this student record.', primary_key=True, serialize=False)),
                ('student_id', models.CharField(help_text='Institutional student ID, auto-generated or assigned during enrollment.', max_length=30, unique=True)),
                ('roll_number', models.CharField(db_index=True, help_text='Examination roll number, unique across the institution.', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Roll number must be 3-20 characters: uppercase letters, digits, hyphens, or slashes.', regex='^[A-Z0-9\\-\\/]{3,20}$')])),
                ('full_name', models.CharField(help_text='Full legal name of the student.', max_length=200)),
                ('first_name', models.CharField(blank=True, default='', help_text='First name.', max_length=100)),
                ('last_name', models.CharField(blank=True, default='', help_text='Last name or surname.', max_length=100)),
                ('institutional_email', models.EmailField(help_text='Institutional email address (e.g., @college.edu).', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('personal_email', models.EmailField(blank=True, default='', help_text='Personal email address.', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, default='', help_text='Primary phone number.', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7 to 15 digits, optionally starting with +).', regex='^\\+?[1-9]\\d{6,14}$')])),
                ('alternate_phone', models.CharField(blank=True, default='', help_text='Secondary or guardian phone number.', max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7 to 15 digits, optionally starting with +).', regex='^\\+?[1-9]\\d{6,14}$')])),
                ('admission_year', models.PositiveSmallIntegerField(help_text='Year of admission, e.g., 2023.', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('enrollment_date', models.DateField(default=django.utils.timezone.now, help_text='Date of enrollment.')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], default='prefer_not_to_say', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of birth.', null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('address', models.TextField(blank=True, default='', help_text='Permanent or residential address.')),
                ('guardian_name', models.CharField(blank=True, default='', help_text="Guardian's full name.", max_length=200)),
                ('guardian_phone', models.CharField(blank=True, default='', help_text="Guardian's phone number.", max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7 to 15 digits, optionally starting with +).', regex='^\\+?[1-9]\\d{6,14}$')])),
                ('photo', models.ImageField(blank=True, help_text='Student profile photo (used on hall tickets).', null=True, upload_to='students/photos/%Y/%m/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('graduated', 'Graduated'), ('suspended', 'Suspended'), ('withdrawn', 'Withdrawn'), ('detained', 'Detained')], db_index=True, default='active', help_text='Current enrollment status.', max_length=20)),
                ('is_eligible_for_exam', models.BooleanField(default=True, help_text='Overall exam eligibility flag. Set to False to block exam registration.')),
                ('remarks', models.TextField(blank=True, default='', help_text='Administrative remarks or notes about this student.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(help_text='Academic year of enrollment.', on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.academicyear')),
                ('branch', models.ForeignKey(blank=True, help_text='Branch or specialization.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.branch')),
                ('course', models.ForeignKey(help_text='Academic program/course the student is enrolled in.', on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.course')),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin user who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_created', to=settings.AUTH_USER_MODEL)),
                ('current_semester', models.ForeignKey(help_text='Current semester of the student.', on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.semester')),
                ('department', models.ForeignKey(help_text='Department the student is enrolled in.', on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.department')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Admin user who last updated this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, help_text='Linked user account (managed by M1).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'students_student',
                'ordering': ['roll_number'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('completed', 'Completed'), ('detained', 'Detained'), ('withdrawn', 'Withdrawn')], db_index=True, default='enrolled', max_length=20)),
                ('enrolled_date', models.DateField(default=django.utils.timezone.now)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_records', to='academics.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_records_created', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_records', to='academics.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_records', to='students.student')),
            ],
            options={
                'verbose_name': 'Enrollment Record',
                'verbose_name_plural': 'Enrollment Records',
                'db_table': 'students_enrollment_record',
                'ordering': ['-enrolled_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentImportLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(help_text='Original filename of the CSV.', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial Success')], db_index=True, default='pending', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('successful_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('duplicate_rows', models.PositiveIntegerField(default=0)),
                ('skipped_rows', models.PositiveIntegerField(default=0)),
                ('error_details', models.JSONField(default=list, help_text='List of row-level error dicts: {row, field, error, value}.')),
                ('summary', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_logs', to='academics.academicyear')),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_import_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Import Log',
                'verbose_name_plural': 'Student Import Logs',
                'db_table': 'students_import_log',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['roll_number'], name='idx_student_roll'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_id'], name='idx_student_sid'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['institutional_email'], name='idx_student_email'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['department'], name='idx_student_dept'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['course'], name='idx_student_course'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['branch'], name='idx_student_branch'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['current_semester'], name='idx_student_sem'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['academic_year'], name='idx_student_acyear'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status'], name='idx_student_status'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['admission_year'], name='idx_student_admyear'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['full_name'], name='idx_student_name'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollmentrecord',
            unique_together={('student', 'semester', 'academic_year')},
        ),
    ]
