# Generated by Django 6.1 on 2026-10-09 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('campus_zone', models.CharField(default='Main Campus', max_length=50)),
                ('total_floors', models.PositiveIntegerField(default=4)),
                ('has_elevator', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=30)),
                ('floor', models.IntegerField(default=1)),
                ('room_type', models.CharField(choices=[('lecture_hall', 'Lecture Hall'), ('exam_hall', 'Main Examination Hall'), ('computer_lab', 'Computer Lab'), ('seminar_hall', 'Seminar Hall'), ('drawing_hall', 'Drawing Hall')], default='exam_hall', max_length=30)),
                ('capacity', models.PositiveIntegerField(help_text='Total physical desks/benches')),
                ('usable_capacity', models.PositiveIntegerField(help_text='Usable capacity under safe examination seating')),
                ('rows', models.PositiveIntegerField(default=6, help_text='Number of bench/desk rows in the room')),
                ('columns', models.PositiveIntegerField(default=5, help_text='Number of columns/seats per row')),
                ('is_accessible', models.BooleanField(default=True, help_text='Wheelchair accessible / ramp access')),
                ('has_cctv', models.BooleanField(default=True, help_text='Equipped with surveillance CCTV')),
                ('has_air_conditioning', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='infrastructure.building')),
            ],
            options={
                'ordering': ['building__code', 'room_number'],
                'unique_together': {('building', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='RoomMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(max_length=255)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='infrastructure.room')),
            ],
        ),
        migrations.CreateModel(
            name='RoomAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allotted_students_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('active', 'Active Exam in Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='reserved', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_assignments', to='examinations.examination')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_assignments', to='infrastructure.room')),
            ],
            options={
                'unique_together': {('examination', 'room')},
            },
        ),
    ]
