# Generated by Django 5.1.15 on 2026-10-09 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(default='2025-2026', max_length=20)),
                ('enrolled_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-academic_year', 'semester'],
                'unique_together': {('student', 'semester', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='SubjectRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_approved', models.BooleanField(default=True)),
                ('eligibility_status', models.CharField(choices=[('ELIGIBLE', 'Eligible'), ('ATTENDANCE_SHORTAGE', 'Attendance Shortage (<75%)'), ('FEES_DUE', 'Institutional Fees Pending'), ('SUSPENDED', 'Disciplinary Suspension'), ('DETAINED', 'Academic Detention')], default='ELIGIBLE', max_length=30)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=85.0, max_digits=5)),
                ('internal_marks', models.DecimalField(decimal_places=2, default=22.0, max_digits=5)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_registrations', to='academics.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_registrations', to='students.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='academics.subject')),
            ],
            options={
                'ordering': ['student', 'subject'],
                'unique_together': {('student', 'subject', 'semester')},
            },
        ),
    ]
