# Generated by Django 6.1.2 on 2026-10-09 09:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkRegistrationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('registration_type', models.CharField(choices=[('subject', 'Subject Registration'), ('exam', 'Exam Registration')], max_length=10)),
                ('file_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('partial', 'Partial Success'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('successful_rows', models.PositiveIntegerField(default=0)),
                ('failed_rows', models.PositiveIntegerField(default=0)),
                ('duplicate_rows', models.PositiveIntegerField(default=0)),
                ('error_details', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_jobs', to='academics.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_registration_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk Registration Job',
                'verbose_name_plural': 'Bulk Registration Jobs',
                'db_table': 'm2_bulk_registration_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam_session_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('exam_session_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('registered', 'Registered'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('withdrawn', 'Withdrawn')], db_index=True, default='registered', max_length=20)),
                ('registration_date', models.DateField(default=django.utils.timezone.now)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('hall_ticket_number', models.CharField(blank=True, db_index=True, max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('import_batch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_registrations', to='academics.academicyear')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_registrations_cancelled', to=settings.AUTH_USER_MODEL)),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_registrations_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_registrations', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_registrations', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Exam Registration',
                'verbose_name_plural': 'Exam Registrations',
                'db_table': 'm2_exam_registrations',
                'ordering': ['-registration_date', '-created_at'],
                'indexes': [models.Index(fields=['student', 'academic_year'], name='m2_exam_reg_student_63a4db_idx'), models.Index(fields=['subject', 'exam_session_id'], name='m2_exam_reg_subject_4caa8c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['registered', 'confirmed'])), fields=('student', 'subject', 'academic_year', 'exam_session_id'), name='unique_active_exam_registration')],
            },
        ),
        migrations.CreateModel(
            name='SubjectRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('registered', 'Registered'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('withdrawn', 'Withdrawn')], db_index=True, default='registered', max_length=20)),
                ('registration_date', models.DateField(default=django.utils.timezone.now)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('import_batch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_registrations', to='academics.academicyear')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_registrations_cancelled', to=settings.AUTH_USER_MODEL)),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_registrations_created', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subject_registrations', to='academics.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_registrations', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subject_registrations', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Subject Registration',
                'verbose_name_plural': 'Subject Registrations',
                'db_table': 'm2_subject_registrations',
                'ordering': ['-registration_date', '-created_at'],
                'indexes': [models.Index(fields=['student', 'academic_year'], name='m2_subject__student_d742dc_idx'), models.Index(fields=['subject', 'academic_year'], name='m2_subject__subject_a01771_idx'), models.Index(fields=['status', 'academic_year'], name='m2_subject__status_e91679_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['registered', 'confirmed'])), fields=('student', 'subject', 'academic_year'), name='unique_active_subject_registration')],
            },
        ),
    ]
