# Generated by Django 6.1 on 2026-10-09 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('examinations', '0001_initial'),
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_invigilators', models.PositiveIntegerField(default=1, help_text='Number of faculty needed (e.g. 1 per 25 students)')),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invigilation_requirements', to='examinations.examination')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invigilation_requirements', to='infrastructure.room')),
            ],
            options={
                'unique_together': {('examination', 'room')},
            },
        ),
        migrations.CreateModel(
            name='InvigilatorDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_date', models.DateField()),
                ('role', models.CharField(choices=[('chief_superintendent', 'Chief Invigilator / Superintendent'), ('hall_invigilator', 'Hall Invigilator'), ('reliever_squad', 'Reliever / Flying Squad')], default='hall_invigilator', max_length=30)),
                ('status', models.CharField(choices=[('assigned', 'Assigned & Confirmed'), ('reassigned', 'Reassigned Manually'), ('completed', 'Duty Completed'), ('absent', 'Reported Absent / Replaced')], default='assigned', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invigilator_duties', to='examinations.examination')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invigilator_duties', to='academics.faculty')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invigilator_duties', to='infrastructure.room')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invigilator_duties', to='examinations.timeslot')),
            ],
            options={
                'ordering': ['duty_date', 'time_slot__start_time', 'room__room_number'],
                'unique_together': {('duty_date', 'time_slot', 'faculty'), ('examination', 'room', 'faculty')},
            },
        ),
    ]
