# Generated by Django 6.1.2 on 2026-10-09 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], db_index=True, default='active', help_text='Lifecycle status of this record.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Optional administrative notes.')),
                ('label', models.CharField(help_text='Academic year label, e.g., "2024-2025".', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Label must be in the format YYYY-YYYY, e.g., 2024-2025.', regex='^\\d{4}-\\d{4}$')])),
                ('start_date', models.DateField(help_text='First day of the academic year.')),
                ('end_date', models.DateField(help_text='Last day of the academic year.')),
                ('is_current', models.BooleanField(db_index=True, default=False, help_text='Marks the current active academic year. Only one may be current.')),
            ],
            options={
                'verbose_name': 'Academic Year',
                'verbose_name_plural': 'Academic Years',
                'db_table': 'academics_academic_year',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], db_index=True, default='active', help_text='Lifecycle status of this record.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Optional administrative notes.')),
                ('name', models.CharField(help_text='Full branch name, e.g., "Computer Science and Engineering".', max_length=200)),
                ('code', models.CharField(help_text='Short unique branch code, e.g., "CSE".', max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_code', message='Code must be 2-20 characters, uppercase letters, digits, hyphens, or underscores only.', regex='^[A-Z0-9_\\-]{2,20}$')])),
                ('description', models.TextField(blank=True, default='', help_text='Description of the branch.')),
                ('intake_capacity', models.PositiveSmallIntegerField(blank=True, help_text='Maximum annual intake for this branch.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)])),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'db_table': 'academics_branch',
                'ordering': ['course__code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], db_index=True, default='active', help_text='Lifecycle status of this record.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Optional administrative notes.')),
                ('name', models.CharField(help_text='Full name of the course, e.g., "Bachelor of Technology".', max_length=200)),
                ('code', models.CharField(help_text='Short unique code for this course, e.g., "BTECH".', max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_code', message='Code must be 2-20 characters, uppercase letters, digits, hyphens, or underscores only.', regex='^[A-Z0-9_\\-]{2,20}$')])),
                ('short_name', models.CharField(blank=True, default='', help_text='Abbreviated name, e.g., "B.Tech".', max_length=50)),
                ('duration_years', models.PositiveSmallIntegerField(choices=[(1, '1 Year'), (2, '2 Years'), (3, '3 Years'), (4, '4 Years'), (5, '5 Years')], default=4, help_text='Total duration of the course in years.')),
                ('total_semesters', models.PositiveSmallIntegerField(help_text='Total number of semesters in this course.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('description', models.TextField(blank=True, default='', help_text='Description of the course and its objectives.')),
                ('is_postgraduate', models.BooleanField(default=False, help_text='Indicates if this is a postgraduate course.')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'academics_course',
                'ordering': ['department__code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], db_index=True, default='active', help_text='Lifecycle status of this record.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Optional administrative notes.')),
                ('name', models.CharField(help_text='Full name of the department, e.g., "Computer Science and Engineering".', max_length=150, unique=True)),
                ('code', models.CharField(help_text='Short unique department code, e.g., "CSE".', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_code', message='Code must be 2-20 characters, uppercase letters, digits, hyphens, or underscores only.', regex='^[A-Z0-9_\\-]{2,20}$')])),
                ('email', models.EmailField(blank=True, default='', help_text='Official department email address.', max_length=254)),
                ('phone', models.CharField(blank=True, default='', help_text='Department contact phone number.', max_length=20)),
                ('established_year', models.PositiveSmallIntegerField(blank=True, help_text='Year the department was established.', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('description', models.TextField(blank=True, default='', help_text='Brief description of the department.')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'academics_department',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], db_index=True, default='active', help_text='Lifecycle status of this record.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Optional administrative notes.')),
                ('semester_number', models.PositiveSmallIntegerField(help_text='Semester number, e.g., 1, 2, 3.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('name', models.CharField(blank=True, default='', help_text='Descriptive name, e.g., "First Semester".', max_length=100)),
                ('start_date', models.DateField(blank=True, help_text='Planned start date of this semester.', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Planned end date of this semester.', null=True)),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
                'db_table': 'academics_semester',
                'ordering': ['course__code', 'branch__code', 'semester_number'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], db_index=True, default='active', help_text='Lifecycle status of this record.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Optional administrative notes.')),
                ('code', models.CharField(help_text='Unique subject code, e.g., "CS301".', max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_code', message='Code must be 2-20 characters, uppercase letters, digits, hyphens, or underscores only.', regex='^[A-Z0-9_\\-]{2,20}$')])),
                ('name', models.CharField(help_text='Full subject name, e.g., "Data Structures and Algorithms".', max_length=200)),
                ('short_name', models.CharField(blank=True, default='', help_text='Abbreviated subject name for display in tight spaces.', max_length=50)),
                ('subject_type', models.CharField(choices=[('core', 'Core'), ('elective', 'Elective'), ('lab', 'Laboratory'), ('project', 'Project'), ('seminar', 'Seminar'), ('audit', 'Audit')], db_index=True, default='core', help_text='Type of subject: core, elective, lab, project, etc.', max_length=20)),
                ('credits', models.PositiveSmallIntegerField(default=3, help_text='Credit value for this subject.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('lecture_hours_per_week', models.PositiveSmallIntegerField(default=0, help_text='Number of lecture hours per week.', validators=[django.core.validators.MaxValueValidator(10)])),
                ('lab_hours_per_week', models.PositiveSmallIntegerField(default=0, help_text='Number of lab hours per week.', validators=[django.core.validators.MaxValueValidator(10)])),
                ('is_elective_group', models.BooleanField(default=False, help_text='Marks this subject as belonging to an elective group.')),
                ('elective_group_name', models.CharField(blank=True, default='', help_text='Name of the elective group, if applicable.', max_length=100)),
                ('description', models.TextField(blank=True, default='', help_text='Syllabus summary or description.')),
                ('is_external_exam', models.BooleanField(default=True, help_text='Indicates if this subject has an external examination.')),
                ('is_internal_exam', models.BooleanField(default=True, help_text='Indicates if this subject has internal assessment.')),
                ('max_external_marks', models.PositiveSmallIntegerField(default=100, help_text='Maximum marks for external examination.', validators=[django.core.validators.MaxValueValidator(500)])),
                ('max_internal_marks', models.PositiveSmallIntegerField(default=50, help_text='Maximum marks for internal assessment.', validators=[django.core.validators.MaxValueValidator(500)])),
                ('pass_marks_external', models.PositiveSmallIntegerField(default=35, help_text='Minimum marks to pass external examination.', validators=[django.core.validators.MaxValueValidator(500)])),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'academics_subject',
                'ordering': ['department__code', 'course__code', 'semester__semester_number', 'code'],
            },
        ),
    ]
