# Generated by Django 6.1.2 on 2026-10-09 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='course',
            field=models.ForeignKey(help_text='The course this branch belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='academics.course'),
        ),
        migrations.AddField(
            model_name='department',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='head_of_department',
            field=models.ForeignKey(blank=True, help_text='Faculty user who is the Head of Department.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(help_text='The department this course belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='academics.department'),
        ),
        migrations.AddField(
            model_name='semester',
            name='academic_year',
            field=models.ForeignKey(blank=True, help_text='The academic year this semester is offered in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semesters', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='semester',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='The branch this semester belongs to, if branch-specific.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='semesters', to='academics.branch'),
        ),
        migrations.AddField(
            model_name='semester',
            name='course',
            field=models.ForeignKey(help_text='The course this semester belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='semesters', to='academics.course'),
        ),
        migrations.AddField(
            model_name='semester',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='semester',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch for which this subject is offered (if branch-specific).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='academics.branch'),
        ),
        migrations.AddField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(help_text='Course in which this subject is taught.', on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='academics.course'),
        ),
        migrations.AddField(
            model_name='subject',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(help_text='Department offering this subject.', on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='academics.department'),
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.ForeignKey(help_text='The semester in which this subject is offered.', on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='academics.semester'),
        ),
        migrations.AddField(
            model_name='subject',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['label'], name='idx_acyear_label'),
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['is_current'], name='idx_acyear_current'),
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['status'], name='idx_acyear_status'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['code'], name='idx_branch_code'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['course'], name='idx_branch_course'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['status'], name='idx_branch_status'),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('course', 'code')},
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['code'], name='idx_dept_code'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['status'], name='idx_dept_status'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['name'], name='idx_dept_name'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['code'], name='idx_course_code'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['department'], name='idx_course_dept'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['status'], name='idx_course_status'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('department', 'code')},
        ),
        migrations.AddIndex(
            model_name='semester',
            index=models.Index(fields=['course', 'semester_number'], name='idx_sem_course_num'),
        ),
        migrations.AddIndex(
            model_name='semester',
            index=models.Index(fields=['branch'], name='idx_sem_branch'),
        ),
        migrations.AddIndex(
            model_name='semester',
            index=models.Index(fields=['status'], name='idx_sem_status'),
        ),
        migrations.AddIndex(
            model_name='semester',
            index=models.Index(fields=['academic_year'], name='idx_sem_acyear'),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('course', 'branch', 'semester_number')},
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['code'], name='idx_subject_code'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['department'], name='idx_subject_dept'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['course', 'semester'], name='idx_subject_course_sem'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['subject_type'], name='idx_subject_type'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['status'], name='idx_subject_status'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('course', 'branch', 'semester', 'code')},
        ),
    ]
