# Generated by Django 5.1.15 on 2026-10-09 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examinations', '0001_initial'),
        ('faculty', '0001_initial'),
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvigilatorDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_role', models.CharField(choices=[('CHIEF', 'Chief Superintendent'), ('INVIGILATOR', 'Hall Invigilator'), ('RELIEVER', 'Reliever / Squad')], default='INVIGILATOR', max_length=20)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Duty Assigned'), ('CONFIRMED', 'Confirmed by Faculty'), ('COMPLETED', 'Duty Completed'), ('REPLACED', 'Replaced'), ('ABSENT', 'Reported Absent')], default='ASSIGNED', max_length=20)),
                ('reporting_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invigilator_duties', to='examinations.examsubject')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invigilation_duties', to='faculty.facultyprofile')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invigilator_duties', to='infrastructure.examinationroom')),
            ],
            options={
                'ordering': ['exam_subject__planned_date', 'room__room_number'],
                'unique_together': {('exam_subject', 'room', 'faculty')},
            },
        ),
    ]
