# Generated by Django 6.1.2 on 2026-10-09 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examinations', '0001_initial'),
        ('faculty', '0001_initial'),
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvigilatorDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField(db_index=True)),
                ('duty_role', models.CharField(choices=[('CHIEF_SUPERINTENDENT', 'Chief Superintendent'), ('HALL_INVIGILATOR', 'Hall Invigilator'), ('RELIEVER', 'Relieving Invigilator'), ('SQUAD_MEMBER', 'Flying Squad Officer')], default='HALL_INVIGILATOR', max_length=30)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('CONFIRMED', 'Confirmed by Faculty'), ('COMPLETED', 'Duty Completed'), ('ABSENT', 'Absent / Reassigned')], default='ASSIGNED', max_length=20)),
                ('is_notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invigilator_duties', to='faculty.facultyprofile')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duty_invigilators', to='infrastructure.room')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invigilator_duties', to='examinations.examsession')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='examinations.timeslot')),
            ],
            options={
                'verbose_name': 'Invigilator Duty',
                'verbose_name_plural': 'Invigilator Duties',
                'ordering': ['exam_date', 'time_slot__start_time', 'faculty__first_name'],
                'unique_together': {('faculty', 'exam_date', 'time_slot')},
            },
        ),
    ]
