# Generated by Django 6.1.2 on 2026-10-09 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Shift 1 (09:30 AM - 12:30 PM)', max_length=100)),
                ('code', models.CharField(db_index=True, help_text='e.g. M1, A1, E1', max_length=30, unique=True)),
                ('shift', models.CharField(choices=[('MORNING', 'Morning Shift'), ('AFTERNOON', 'Afternoon Shift'), ('EVENING', 'Evening Shift')], default='MORNING', max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=180, help_text='Duration in minutes (e.g. 180 min = 3 hrs)')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Time Slot',
                'verbose_name_plural': 'Time Slots',
                'ordering': ['sort_order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. End Semester Examinations - Autumn 2025', max_length=200)),
                ('code', models.CharField(db_index=True, help_text='e.g. ESE-AUT-2025', max_length=50, unique=True)),
                ('academic_year', models.CharField(default='2025-2026', max_length=20)),
                ('term', models.CharField(choices=[('ODD', 'Odd Term'), ('EVEN', 'Even Term'), ('SUMMER', 'Summer Term')], default='ODD', max_length=10)),
                ('session_type', models.CharField(choices=[('END_TERM', 'End Semester Final Examination'), ('MID_TERM', 'Mid-Term / Continuous Assessment'), ('SUPPLEMENTARY', 'Supplementary / Arrear Examination'), ('SPECIAL_IMPROVEMENT', 'Special Improvement Examination')], default='END_TERM', max_length=30)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft (Configuring)'), ('VALIDATING', 'Validating Constraints'), ('VALIDATED', 'Validated & Conflict-Free'), ('APPROVED', 'Approved by Controller of Exams'), ('PUBLISHED', 'Published to Campus & Students'), ('IN_PROGRESS', 'Examination In Progress'), ('COMPLETED', 'Completed & Evaluated'), ('ARCHIVED', 'Archived (Historical Record)')], db_index=True, default='DRAFT', max_length=30)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('instructions', models.TextField(blank=True, default='Students must carry their physical Hall Ticket and College ID. Electronic devices strictly prohibited.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_exam_sessions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exam_sessions', to=settings.AUTH_USER_MODEL)),
                ('departments', models.ManyToManyField(blank=True, related_name='exam_sessions', to='academics.department')),
            ],
            options={
                'verbose_name': 'Examination Session',
                'verbose_name_plural': 'Examination Sessions',
                'ordering': ['-start_date', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ExamSessionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('state_from', models.CharField(blank=True, default='', max_length=50)),
                ('state_to', models.CharField(blank=True, default='', max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_logs', to='examinations.examsession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam Session History',
                'verbose_name_plural': 'Exam Session History Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SchedulingConstraintConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_exams_per_student_per_day', models.PositiveIntegerField(default=1)),
                ('min_study_gap_days_hard', models.PositiveIntegerField(default=1, help_text='Minimum rest days for heavy difficulty subjects')),
                ('min_study_gap_days_general', models.PositiveIntegerField(default=0)),
                ('prevent_cross_branch_clashes', models.BooleanField(default=True)),
                ('allow_saturday_exams', models.BooleanField(default=True)),
                ('allow_sunday_exams', models.BooleanField(default=False)),
                ('max_concurrent_rooms', models.PositiveIntegerField(default=25)),
                ('enforce_room_capacity_limits', models.BooleanField(default=True)),
                ('enforce_invigilator_limits', models.BooleanField(default=True)),
                ('consecutive_hard_subjects_penalty', models.PositiveIntegerField(default=50)),
                ('solver_timeout_seconds', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='constraint_config', to='examinations.examsession')),
            ],
            options={
                'verbose_name': 'Scheduling Constraint Configuration',
                'verbose_name_plural': 'Scheduling Constraint Configurations',
            },
        ),
        migrations.CreateModel(
            name='ExamSubjectConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_students_count', models.PositiveIntegerField(default=60)),
                ('max_marks', models.PositiveIntegerField(default=100)),
                ('passing_marks', models.PositiveIntegerField(default=40)),
                ('question_paper_code', models.CharField(blank=True, default='', max_length=50)),
                ('difficulty_weight', models.PositiveIntegerField(default=3, help_text='Scale 1 (easiest) to 5 (most intense)')),
                ('is_mandatory', models.BooleanField(default=True)),
                ('is_practical', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='dependent_exam_configs', to='examinations.examsubjectconfig')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configured_subjects', to='examinations.examsession')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_configs', to='academics.subject')),
                ('preferred_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_subjects', to='examinations.timeslot')),
            ],
            options={
                'verbose_name': 'Exam Subject Configuration',
                'verbose_name_plural': 'Exam Subject Configurations',
                'ordering': ['subject__semester_number', 'subject__code'],
                'unique_together': {('session', 'subject')},
            },
        ),
    ]
