# Generated by Django 5.1.15 on 2026-10-09 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examinations', '0001_initial'),
        ('infrastructure', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_num', models.IntegerField()),
                ('col_num', models.IntegerField()),
                ('seat_label', models.CharField(max_length=20)),
                ('is_usable', models.BooleanField(default=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='infrastructure.examinationroom')),
            ],
            options={
                'ordering': ['row_num', 'col_num'],
                'unique_together': {('room', 'row_num', 'col_num')},
            },
        ),
        migrations.CreateModel(
            name='SeatingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Plan'), ('GENERATED', 'Generated & Validated'), ('LOCKED', 'Locked for Examination')], default='DRAFT', max_length=20)),
                ('spacing_rule', models.CharField(default='ALTERNATE_COLS', help_text='ALTERNATE_COLS or CHECKERBOARD', max_length=50)),
                ('total_allocated', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seating_plans', to='examinations.examsubject')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seating_plans', to='infrastructure.examinationroom')),
            ],
            options={
                'ordering': ['exam_subject__planned_date', 'room__room_number'],
                'unique_together': {('exam_subject', 'room')},
            },
        ),
        migrations.CreateModel(
            name='SeatAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='seating.seat')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_allocations', to='students.studentprofile')),
                ('seating_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='seating.seatingplan')),
            ],
            options={
                'ordering': ['seat__row_num', 'seat__col_num'],
                'unique_together': {('seating_plan', 'seat'), ('seating_plan', 'student')},
            },
        ),
    ]
