# Generated by Django 6.1.2 on 2026-10-09 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examinations', '0001_initial'),
        ('faculty', '0001_initial'),
        ('infrastructure', '0001_initial'),
        ('scheduling', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField(db_index=True)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('total_rooms_used', models.PositiveIntegerField(default=0)),
                ('spacing_rule', models.CharField(default='ALTERNATE_SEATS', help_text='ALTERNATE_SEATS, CROSS_DEPARTMENT', max_length=50)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seating_plans', to='examinations.examsession')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='examinations.timeslot')),
            ],
            options={
                'verbose_name': 'Seating Plan',
                'verbose_name_plural': 'Seating Plans',
                'ordering': ['exam_date', 'time_slot__start_time'],
                'unique_together': {('session', 'exam_date', 'time_slot')},
            },
        ),
        migrations.CreateModel(
            name='RoomAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_count', models.PositiveIntegerField(default=0)),
                ('is_confirmed', models.BooleanField(default=True)),
                ('primary_invigilator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_duties', to='faculty.facultyprofile')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_allocations', to='infrastructure.room')),
                ('seating_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_allocations', to='seating.seatingplan')),
            ],
            options={
                'verbose_name': 'Room Allocation',
                'verbose_name_plural': 'Room Allocations',
                'ordering': ['room__block__code', 'room__room_number'],
                'unique_together': {('seating_plan', 'room')},
            },
        ),
        migrations.CreateModel(
            name='SeatAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_label', models.CharField(help_text='e.g. A-1, B-4, R1-C2', max_length=20)),
                ('row_number', models.PositiveIntegerField(default=1)),
                ('column_number', models.PositiveIntegerField(default=1)),
                ('desk_number', models.PositiveIntegerField(default=1)),
                ('room_allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_assignments', to='seating.roomallocation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_seats', to='students.student')),
                ('timetable_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_assignments', to='scheduling.timetableentry')),
            ],
            options={
                'verbose_name': 'Seat Assignment',
                'verbose_name_plural': 'Seat Assignments',
                'ordering': ['row_number', 'column_number'],
                'unique_together': {('room_allocation', 'student')},
            },
        ),
    ]
