# Generated by Django 6.1.2 on 2026-10-09 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('total_floors', models.PositiveIntegerField(default=4)),
                ('campus_zone', models.CharField(blank=True, default='North Wing', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Academic Block',
                'verbose_name_plural': 'Academic Blocks',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(db_index=True, max_length=50)),
                ('floor_number', models.PositiveIntegerField(default=1)),
                ('room_type', models.CharField(choices=[('EXAM_HALL', 'Examination Hall'), ('CLASSROOM', 'Standard Classroom'), ('COMPUTER_LAB', 'Computer Lab / Digital Hall'), ('DRAWING_HALL', 'Engineering Drawing Hall'), ('AUDITORIUM', 'Auditorium / Seminar Hall')], default='CLASSROOM', max_length=30)),
                ('rows_count', models.PositiveIntegerField(default=6)),
                ('columns_count', models.PositiveIntegerField(default=6)),
                ('total_capacity', models.PositiveIntegerField(default=36)),
                ('usable_exam_capacity', models.PositiveIntegerField(default=30)),
                ('has_cctv', models.BooleanField(default=True)),
                ('is_accessible', models.BooleanField(default=True)),
                ('has_power_backup', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='infrastructure.block')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['block__code', 'room_number'],
                'unique_together': {('block', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='RoomAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('slot_shift', models.CharField(default='FULL_DAY', max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='infrastructure.room')),
            ],
            options={
                'verbose_name': 'Room Availability',
                'verbose_name_plural': 'Room Availabilities',
                'ordering': ['date', 'room__room_number'],
                'unique_together': {('room', 'date', 'slot_shift')},
            },
        ),
    ]
