# Generated by Django 5.1.15 on 2026-10-09 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('floors_count', models.IntegerField(default=4)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='ExaminationRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=30, unique=True)),
                ('floor', models.IntegerField(default=1)),
                ('room_type', models.CharField(choices=[('LECTURE_HALL', 'Lecture Hall'), ('CLASSROOM', 'Standard Classroom'), ('DRAWING_HALL', 'Drawing Hall'), ('AUDITORIUM', 'Auditorium'), ('SEMINAR_HALL', 'Seminar Hall')], default='CLASSROOM', max_length=30)),
                ('total_capacity', models.IntegerField(default=60)),
                ('usable_capacity', models.IntegerField(default=30, help_text='Capacity after applying exam spacing')),
                ('rows', models.IntegerField(default=5)),
                ('columns', models.IntegerField(default=6)),
                ('has_cctv', models.BooleanField(default=True)),
                ('is_accessible', models.BooleanField(default=True, help_text='Wheelchair accessible')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('MAINTENANCE', 'Under Maintenance'), ('RESERVED', 'Reserved')], default='AVAILABLE', max_length=20)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='infrastructure.building')),
            ],
            options={
                'ordering': ['building', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='RoomAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot_name', models.CharField(default='Morning', max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='infrastructure.examinationroom')),
            ],
            options={
                'verbose_name_plural': 'Room Availabilities',
                'unique_together': {('room', 'date', 'time_slot_name')},
            },
        ),
    ]
