# Generated by Django 6.1.2 on 2026-10-09 05:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examinations', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('barcode_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('is_eligible', models.BooleanField(default=True)),
                ('eligibility_remarks', models.CharField(blank=True, default='Cleared all academic & attendance requirements.', max_length=255)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('last_downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_tickets', to='examinations.examsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_tickets', to='students.student')),
            ],
            options={
                'verbose_name': 'Hall Ticket',
                'verbose_name_plural': 'Hall Tickets',
                'ordering': ['student__register_number'],
                'unique_together': {('session', 'student')},
            },
        ),
    ]
