# Generated by Django 5.1.15 on 2026-10-09 05:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examinations', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=60, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('verification_hash', models.CharField(default=uuid.uuid4, max_length=64)),
                ('is_blocked', models.BooleanField(default=False)),
                ('block_reason', models.TextField(blank=True, default='')),
                ('download_count', models.IntegerField(default=0)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='hall_tickets/')),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_tickets', to='examinations.examsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_tickets', to='students.studentprofile')),
            ],
            options={
                'ordering': ['student__roll_no'],
                'unique_together': {('student', 'exam_session')},
            },
        ),
        migrations.CreateModel(
            name='HallTicketEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('time_slot_str', models.CharField(max_length=100)),
                ('room_number', models.CharField(max_length=30)),
                ('seat_label', models.CharField(max_length=20)),
                ('exam_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examinations.examsubject')),
                ('hall_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='halltickets.hallticket')),
            ],
            options={
                'ordering': ['exam_date', 'time_slot_str'],
            },
        ),
    ]
