# Generated by Django 6.1.2 on 2026-10-09 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('roll_number', models.CharField(blank=True, default='', max_length=50)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('current_semester_number', models.PositiveIntegerField(default=1)),
                ('admission_year', models.CharField(default='2024', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('GRADUATED', 'Graduated'), ('INACTIVE', 'Inactive / On Leave')], default='ACTIVE', max_length=20)),
                ('is_eligible_for_exams', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.branch')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['register_number'],
            },
        ),
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(default='2025-2026', max_length=20)),
                ('enrolled_on', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='academics.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Enrollment',
                'verbose_name_plural': 'Student Enrollments',
                'ordering': ['-academic_year', 'semester__semester_number'],
                'unique_together': {('student', 'semester', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='SubjectRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(default='2025-2026', max_length=20)),
                ('semester_number', models.PositiveIntegerField(default=1)),
                ('is_regular', models.BooleanField(default=True, help_text='True for regular term, False for supplementary/backlog')),
                ('eligibility_status', models.CharField(choices=[('ELIGIBLE', 'Eligible'), ('LOW_ATTENDANCE', 'Debarred (Low Attendance < 75%)'), ('FEES_PENDING', 'Hold (Fees Pending)'), ('DEBARRED', 'Debarred (Disciplinary)')], default='ELIGIBLE', max_length=30)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=85.0, max_digits=5)),
                ('is_approved', models.BooleanField(default=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_registrations', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_registrations', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Subject Registration',
                'verbose_name_plural': 'Subject Registrations',
                'ordering': ['student__register_number', 'subject__code'],
                'unique_together': {('student', 'subject', 'academic_year')},
            },
        ),
    ]
