# Generated by Django 6.1 on 2026-10-09 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('examinations', '0001_initial'),
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.PositiveIntegerField(help_text='1-indexed row number')),
                ('col_index', models.PositiveIntegerField(help_text='1-indexed column number')),
                ('seat_label', models.CharField(help_text='e.g. A1, A2 or R1-C1', max_length=20)),
                ('is_usable', models.BooleanField(default=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='infrastructure.room')),
            ],
            options={
                'ordering': ['room', 'row_index', 'col_index'],
                'unique_together': {('room', 'row_index', 'col_index')},
            },
        ),
        migrations.CreateModel(
            name='SeatingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_title', models.CharField(blank=True, default='', max_length=200)),
                ('spacing_rule', models.CharField(choices=[('consecutive', 'Standard Consecutive (Dense)'), ('alternate_gap', 'Alternate Seat Gap (50% Density)'), ('checkerboard', 'Checkerboard Diagonal Pattern'), ('department_separated', 'Cross-Department Separation (Anti-Cheating)')], default='department_separated', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft Plan'), ('generated', 'Generated Automatically'), ('validated', 'Validated & Conflict-Free'), ('approved', 'Approved & Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('total_allocated', models.PositiveIntegerField(default=0)),
                ('total_unallocated', models.PositiveIntegerField(default=0)),
                ('capacity_shortage', models.PositiveIntegerField(default=0)),
                ('validation_status', models.CharField(default='Pending', max_length=50)),
                ('validation_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('examination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seating_plan', to='examinations.examination')),
            ],
        ),
        migrations.CreateModel(
            name='SeatAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_label', models.CharField(max_length=20)),
                ('allocation_type', models.CharField(choices=[('auto', 'Automatic Engine Allocation'), ('manual_swap', 'Manual Seat Adjustment / Swap'), ('special_accommodation', 'Special Accessibility Accommodation')], default='auto', max_length=30)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_allocations', to='examinations.examination')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_allocations', to='infrastructure.room')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='seating.seat')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_allocations', to='academics.student')),
                ('seating_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='seating.seatingplan')),
            ],
            options={
                'ordering': ['room', 'seat__row_index', 'seat__col_index'],
                'unique_together': {('examination', 'room', 'seat'), ('examination', 'student')},
            },
        ),
    ]
