# Generated by Django 6.1.2 on 2026-10-09 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('examinations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Generated'), ('VALIDATING', 'Validating Conflicts'), ('VALIDATED', 'Validated & Conflict-Free'), ('APPROVED', 'Approved by Controller of Exams'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20)),
                ('is_conflict_free', models.BooleanField(default=False)),
                ('clash_count', models.PositiveIntegerField(default=0)),
                ('total_exams_scheduled', models.PositiveIntegerField(default=0)),
                ('total_slots_used', models.PositiveIntegerField(default=0)),
                ('solver_duration_ms', models.FloatField(default=0.0)),
                ('solver_iterations', models.PositiveIntegerField(default=0)),
                ('solver_outcome', models.CharField(default='NOT_RUN', max_length=50)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_timetables', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_timetables', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='examinations.examsession')),
            ],
            options={
                'verbose_name': 'Timetable',
                'verbose_name_plural': 'Timetables',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchedulingClash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clash_type', models.CharField(choices=[('STUDENT_OVERLAP', 'Student Double-Booking'), ('BRANCH_SEM_OVERLAP', 'Branch & Semester Overlap'), ('ROOM_CAPACITY_DEFICIT', 'Room Capacity Deficit'), ('FACULTY_UNAVAILABLE', 'Invigilator Availability Shortage'), ('STUDY_GAP_VIOLATION', 'Insufficient Study Gap (Soft Constraint)'), ('CONSECUTIVE_DIFFICULT', 'Consecutive Difficult Exams (Soft Constraint)')], default='STUDENT_OVERLAP', max_length=30)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical (Mandatory Hard Clash)'), ('HIGH', 'High (Capacity/Resource Risk)'), ('MEDIUM', 'Medium (Soft Constraint Violation)'), ('LOW', 'Low (Sub-optimal Spacing)')], default='CRITICAL', max_length=20)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('affected_students_count', models.PositiveIntegerField(default=0)),
                ('affected_student_names', models.JSONField(blank=True, default=list)),
                ('suggested_resolution', models.TextField(blank=True, default='')),
                ('is_resolved', models.BooleanField(default=False)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('subject_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clashes_as_primary', to='academics.subject')),
                ('subject_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clashes_as_secondary', to='academics.subject')),
                ('time_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='examinations.timeslot')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clashes', to='scheduling.timetable')),
            ],
            options={
                'verbose_name': 'Scheduling Clash',
                'verbose_name_plural': 'Scheduling Clashes',
                'ordering': ['-severity', 'exam_date'],
            },
        ),
        migrations.CreateModel(
            name='TimetableRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.CharField(max_length=20)),
                ('change_summary', models.TextField()),
                ('diff_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='scheduling.timetable')),
            ],
            options={
                'verbose_name': 'Timetable Revision',
                'verbose_name_plural': 'Timetable Revisions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField(db_index=True)),
                ('is_manual_override', models.BooleanField(default=False)),
                ('has_conflict', models.BooleanField(default=False)),
                ('conflict_details', models.CharField(blank=True, default='', max_length=255)),
                ('expected_students', models.PositiveIntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='examinations.examsubjectconfig')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_entries', to='examinations.timeslot')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='scheduling.timetable')),
            ],
            options={
                'verbose_name': 'Timetable Entry',
                'verbose_name_plural': 'Timetable Entries',
                'ordering': ['exam_date', 'time_slot__start_time', 'subject_config__subject__code'],
                'unique_together': {('timetable', 'subject_config')},
            },
        ),
    ]
