# Generated by Django 5.1.15 on 2026-10-09 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examinations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Schedule'), ('VALIDATED', 'Validated (Conflict-Free)'), ('APPROVED', 'Approved by Controller of Examinations'), ('PUBLISHED', 'Published to Faculty & Students'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('total_subjects_count', models.IntegerField(default=0)),
                ('scheduled_count', models.IntegerField(default=0)),
                ('conflict_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_timetables', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_timetables', to=settings.AUTH_USER_MODEL)),
                ('exam_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='examinations.examsession')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SchedulingConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(choices=[('STUDENT_CLASH', 'Student Double-Booking'), ('ROOM_OVERFLOW', 'Room Capacity Overflow'), ('SLOT_UNAVAILABLE', 'Slot Unavailable'), ('GAP_VIOLATION', 'Insufficient Gap Rule')], default='STUDENT_CLASH', max_length=30)),
                ('description', models.TextField()),
                ('affected_students_count', models.IntegerField(default=0)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_subject_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clashes_as_first', to='examinations.examsubject')),
                ('exam_subject_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clashes_as_second', to='examinations.examsubject')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='scheduling.timetable')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.IntegerField()),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='scheduling.timetable')),
            ],
            options={
                'ordering': ['-revision_number'],
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField()),
                ('is_manually_adjusted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='examinations.examsubject')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='examinations.timeslot')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='scheduling.timetable')),
            ],
            options={
                'ordering': ['exam_date', 'time_slot__start_time'],
                'unique_together': {('timetable', 'exam_subject')},
            },
        ),
    ]
