# Generated by Django 6.1.2 on 2026-10-09 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('designation', models.CharField(choices=[('PROFESSOR', 'Professor'), ('ASSOC_PROF', 'Associate Professor'), ('ASST_PROF', 'Assistant Professor'), ('LECTURER', 'Lecturer / Adjunct'), ('RESEARCH_FELLOW', 'Research Fellow / Teaching Assistant')], default='ASST_PROF', max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On Leave'), ('SABBATICAL', 'Sabbatical'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=20)),
                ('max_duties_per_session', models.PositiveIntegerField(default=10)),
                ('current_duties_count', models.PositiveIntegerField(default=0)),
                ('specialization', models.CharField(blank=True, default='', max_length=200)),
                ('is_eligible_for_invigilation', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_members', to='academics.department')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Faculty Profile',
                'verbose_name_plural': 'Faculty Profiles',
                'ordering': ['department__name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='FacultyLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('leave_type', models.CharField(default='Medical / Personal', max_length=50)),
                ('reason', models.TextField(blank=True, default='')),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='faculty.facultyprofile')),
            ],
            options={
                'verbose_name': 'Faculty Leave',
                'verbose_name_plural': 'Faculty Leaves',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FacultyAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('slot_shift', models.CharField(choices=[('MORNING', 'Morning Shift'), ('AFTERNOON', 'Afternoon Shift'), ('EVENING', 'Evening Shift'), ('FULL_DAY', 'Full Day')], default='FULL_DAY', max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='faculty.facultyprofile')),
            ],
            options={
                'verbose_name': 'Faculty Availability',
                'verbose_name_plural': 'Faculty Availabilities',
                'ordering': ['date', 'faculty__first_name'],
                'unique_together': {('faculty', 'date', 'slot_shift')},
            },
        ),
    ]
