# Generated by Django 5.1.15 on 2026-10-09 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=30, unique=True)),
                ('designation', models.CharField(choices=[('PROFESSOR', 'Professor'), ('ASSOC_PROFESSOR', 'Associate Professor'), ('ASST_PROFESSOR', 'Assistant Professor'), ('LECTURER', 'Lecturer'), ('LAB_INSTRUCTOR', 'Lab Instructor')], default='ASST_PROFESSOR', max_length=30)),
                ('qualification', models.CharField(blank=True, default='', max_length=100)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('emergency_contact', models.CharField(blank=True, default='', max_length=20)),
                ('max_duties_per_term', models.IntegerField(default=6)),
                ('is_available_for_duty', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_members', to='academics.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['employee_id'],
            },
        ),
        migrations.CreateModel(
            name='FacultyLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='faculty.facultyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot_name', models.CharField(default='Morning', help_text='Morning, Afternoon or specific slot', max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='faculty.facultyprofile')),
            ],
            options={
                'verbose_name_plural': 'Faculty Availabilities',
                'unique_together': {('faculty', 'date', 'time_slot_name')},
            },
        ),
    ]
